import { TypePoints, TypeHidden, TypeMeta, TypeState, TypeTags } from "@cuppazee/db";

const farm: {
  name: string;
  icons: string[];
  id: string;
  munzee_id?: number;
  state: TypeState;
  stage?: number;
  base?: string;

  meta?: TypeMeta;
  points?: TypePoints;
  tags?: TypeTags[];
  hidden?: TypeHidden[];
}[] = [
  {
    name: "Tomato",
    icons: ["tomato"],
    id: "tomato",
    munzee_id: 658,
    state: TypeState.Physical,
    stage: 3,
    base: "tomatoseed",
    hidden: [],
  },
  {
    name: "Ear of Corn",
    icons: ["earofcorn"],
    id: "earofcorn",
    munzee_id: 659,
    state: TypeState.Physical,
    stage: 3,
    base: "cornseed",
    hidden: [],
  },
  {
    name: "Carrot",
    icons: ["carrot"],
    id: "carrot",
    munzee_id: 660,
    state: TypeState.Virtual,
    stage: 3,
    base: "carrotseed",
    hidden: [],
  },
  {
    name: "Peas",
    icons: ["peas"],
    id: "peas",
    munzee_id: 661,
    state: TypeState.Virtual,
    stage: 3,
    base: "peasseed",
    hidden: [],
  },
  {
    name: "Tomato Seed",
    icons: ["tomatoseed"],
    id: "tomatoseed",
    munzee_id: 662,
    state: TypeState.Physical,
    stage: 1,
    base: "tomatoseed",
  },
  {
    name: "Corn Seed",
    icons: ["cornseed"],
    id: "cornseed",
    munzee_id: 663,
    state: TypeState.Physical,
    stage: 1,
    base: "cornseed",
  },
  {
    name: "Carrot Seed",
    icons: ["carrotseed"],
    id: "carrotseed",
    munzee_id: 664,
    state: TypeState.Virtual,
    stage: 1,
    base: "carrotseed",
  },
  {
    name: "Peas Seed",
    icons: ["peasseed"],
    id: "peasseed",
    munzee_id: 665,
    state: TypeState.Virtual,
    stage: 1,
    base: "peasseed",
  },
  {
    name: "Tomato Plant",
    icons: ["tomatoplant"],
    id: "tomatoplant",
    munzee_id: 666,
    state: TypeState.Physical,
    stage: 2,
    base: "tomatoseed",
  },
  {
    name: "Corn Stalk",
    icons: ["cornstalk"],
    id: "cornstalk",
    munzee_id: 667,
    state: TypeState.Physical,
    stage: 2,
    base: "cornseed",
  },
  {
    name: "Carrot Plant",
    icons: ["carrotplant"],
    id: "carrotplant",
    munzee_id: 668,
    state: TypeState.Virtual,
    stage: 2,
    base: "carrotseed",
  },
  {
    name: "Peas Plant",
    icons: ["peasplant"],
    id: "peasplant",
    munzee_id: 669,
    state: TypeState.Virtual,
    stage: 2,
    base: "peasseed",
  },
  {
    name: "Golden Carrot",
    icons: ["goldencarrot"],
    id: "goldencarrot",
    munzee_id: 678,
    state: TypeState.Physical,
    stage: 3,
    base: "goldencarrotseed",
    hidden: [],
  },
  {
    name: "Golden Carrot Seed",
    icons: ["goldencarrotseed"],
    id: "goldencarrotseed",
    munzee_id: 679,
    state: TypeState.Physical,
    stage: 1,
    base: "goldencarrotseed",
  },
  {
    name: "Golden Carrot Plant",
    icons: ["goldencarrotplant"],
    id: "goldencarrotplant",
    munzee_id: 680,
    state: TypeState.Physical,
    stage: 2,
    base: "goldencarrotplant",
  },
  {
    name: "Milk",
    icons: ["milk"],
    id: "milk",
    munzee_id: 684,
    state: TypeState.Physical,
    stage: 3,
    base: "calf",
    hidden: [],
  },
  {
    name: "Bacon",
    icons: ["bacon"],
    id: "bacon",
    munzee_id: 685,
    state: TypeState.Physical,
    stage: 3,
    base: "piglet",
    hidden: [],
  },
  {
    name: "Calf",
    icons: ["calf"],
    id: "calf",
    munzee_id: 698,
    state: TypeState.Physical,
    stage: 1,
    base: "calf",
  },
  {
    name: "Piglet",
    icons: ["piglet"],
    id: "piglet",
    munzee_id: 699,
    state: TypeState.Physical,
    stage: 1,
    base: "piglet",
  },
  {
    name: "Cow",
    icons: ["cow"],
    id: "cow",
    munzee_id: 700,
    state: TypeState.Physical,
    stage: 2,
    base: "calf",
  },
  {
    name: "Pig",
    icons: ["pig"],
    id: "pig",
    munzee_id: 701,
    state: TypeState.Physical,
    stage: 2,
    base: "piglet",
  },
  {
    name: "Championship Horse",
    icons: ["championshiphorse", "horse"],
    id: "championshiphorse",
    munzee_id: 702,
    state: TypeState.Virtual,
    stage: 3,
    base: "colt",
    hidden: [],
  },
  {
    name: "Eggs",
    icons: ["eggs"],
    id: "eggs",
    munzee_id: 703,
    state: TypeState.Virtual,
    stage: 3,
    base: "chick",
    hidden: [],
  },
  {
    name: "Colt",
    icons: ["colt"],
    id: "colt",
    munzee_id: 704,
    state: TypeState.Virtual,
    stage: 1,
    base: "colt",
  },
  {
    name: "Chick",
    icons: ["chick"],
    id: "chick",
    munzee_id: 705,
    state: TypeState.Virtual,
    stage: 1,
    base: "chick",
  },
  {
    name: "Racehorse",
    icons: ["racehorse"],
    id: "racehorse",
    munzee_id: 706,
    state: TypeState.Virtual,
    stage: 2,
    base: "colt",
  },
  {
    name: "Chicken",
    icons: ["chicken"],
    id: "chicken",
    munzee_id: 707,
    state: TypeState.Virtual,
    stage: 2,
    base: "chick",
  },
  {
    name: "Barn",
    icons: ["barn"],
    id: "barn",
    munzee_id: 708,
    state: TypeState.Physical,
    stage: 3,
    base: "lean-toshed",
    hidden: [],
  },
  {
    name: "Tractor",
    icons: ["tractor"],
    id: "tractor",
    munzee_id: 709,
    state: TypeState.Physical,
    stage: 3,
    base: "hoe",
    hidden: [],
  },
  {
    name: "Lean-To Shed",
    icons: ["lean-toshed"],
    id: "lean-toshed",
    munzee_id: 729,
    state: TypeState.Physical,
    stage: 1,
    base: "lean-toshed",
  },
  {
    name: "Garden Shed",
    icons: ["gardenshed"],
    id: "gardenshed",
    munzee_id: 730,
    state: TypeState.Physical,
    stage: 2,
    base: "lean-toshed",
  },
  {
    name: "Hoe",
    icons: ["hoe"],
    id: "hoe",
    munzee_id: 731,
    state: TypeState.Physical,
    stage: 1,
    base: "hoe",
  },
  {
    name: "Plow",
    icons: ["plow"],
    id: "plow",
    munzee_id: 732,
    state: TypeState.Physical,
    stage: 2,
    base: "plow",
  },
  {
    name: "Family",
    icons: ["family"],
    id: "family",
    munzee_id: 735,
    state: TypeState.Virtual,
    stage: 3,
    base: "farmer",
    hidden: [],
  },
  {
    name: "Field",
    icons: ["field"],
    id: "field",
    munzee_id: 736,
    state: TypeState.Virtual,
    stage: 3,
    base: "pottedplant",
    hidden: [],
  },
  {
    name: "Farmer",
    icons: ["farmer"],
    id: "farmer",
    munzee_id: 737,
    state: TypeState.Virtual,
    stage: 1,
    base: "farmer",
  },
  {
    name: "Farmer and Wife",
    icons: ["farmerandwife"],
    id: "farmerandwife",
    munzee_id: 738,
    state: TypeState.Virtual,
    stage: 2,
    base: "farmer",
  },
  {
    name: "Potted Plant",
    icons: ["pottedplant"],
    id: "pottedplant",
    munzee_id: 739,
    state: TypeState.Virtual,
    stage: 1,
    base: "pottedplant",
  },
  {
    name: "Garden",
    icons: ["garden"],
    id: "garden",
    munzee_id: 740,
    state: TypeState.Virtual,
    stage: 2,
    base: "pottedplant",
  },
];

export default farm;
