import { TypePoints, TypeHidden, TypeQuery, TypeMeta, TypeState, TypeTags } from "@cuppazee/db";

const nature: {
  name: string;
  icons: string[];
  id: string;
  munzee_id?: number;
  state: TypeState;
  stage?: number;
  base?: string;

  meta?: TypeMeta;
  points?: TypePoints;
  tags?: TypeTags[];
  hidden?: TypeHidden[];
  lands_on?: TypeQuery[];
}[] = [
  {
    name: "Rose",
    icons: ["rose"],
    id: "rose",
    munzee_id: 1760,
    state: TypeState.Physical,
    stage: 5,
    base: "roseseed",
    hidden: [TypeHidden.Capture, TypeHidden.Deploy],
  },
  {
    name: "Tulip",
    icons: ["tulip"],
    id: "tulip",
    munzee_id: 1761,
    state: TypeState.Physical,
    stage: 5,
    base: "tulipseed",
    hidden: [TypeHidden.Capture, TypeHidden.Deploy],
  },
  {
    name: "Lily",
    icons: ["lily"],
    id: "lily",
    munzee_id: 1774,
    state: TypeState.Physical,
    stage: 5,
    base: "lilyseed",
    hidden: [TypeHidden.Capture, TypeHidden.Deploy],
  },
  {
    name: "Tulip Seed",
    icons: ["tulipseed"],
    id: "tulipseed",
    munzee_id: 1775,
    state: TypeState.Physical,
    stage: 1,
    base: "tulipseed",
  },
  {
    name: "Tulip Germination",
    icons: ["tulipgermination"],
    id: "tulipgermination",
    munzee_id: 1776,
    state: TypeState.Physical,
    stage: 2,
    base: "tulipseed",
  },
  {
    name: "Tulip Growth",
    icons: ["tulipgrowth"],
    id: "tulipgrowth",
    munzee_id: 1777,
    state: TypeState.Physical,
    stage: 3,
    base: "tulipseed",
  },
  {
    name: "Tulip Bud",
    icons: ["tulipbud"],
    id: "tulipbud",
    munzee_id: 1778,
    state: TypeState.Physical,
    stage: 4,
    base: "tulipseed",
  },
  {
    name: "Blue Tulip Blossom",
    icons: ["bluetulipblossom"],
    id: "bluetulipblossom",
    munzee_id: 1779,
    state: TypeState.Physical,
    stage: 5,
    base: "tulipseed",
  },
  {
    name: "Pink Tulip Blossom",
    icons: ["pinktulipblossom"],
    id: "pinktulipblossom",
    munzee_id: 1780,
    state: TypeState.Physical,
    stage: 5,
    base: "tulipseed",
  },
  {
    name: "White Tulip Blossom",
    icons: ["whitetulipblossom"],
    id: "whitetulipblossom",
    munzee_id: 1781,
    state: TypeState.Physical,
    stage: 5,
    base: "tulipseed",
  },
  {
    name: "Rose Seed",
    icons: ["roseseed"],
    id: "roseseed",
    munzee_id: 1782,
    state: TypeState.Physical,
    stage: 1,
    base: "roseseed",
  },
  {
    name: "Rose Germination",
    icons: ["rosegermination"],
    id: "rosegermination",
    munzee_id: 1783,
    state: TypeState.Physical,
    stage: 2,
    base: "roseseed",
  },
  {
    name: "Rose Growth",
    icons: ["rosegrowth"],
    id: "rosegrowth",
    munzee_id: 1784,
    state: TypeState.Physical,
    stage: 3,
    base: "roseseed",
  },
  {
    name: "Rose Bud",
    icons: ["rosebud"],
    id: "rosebud",
    munzee_id: 1785,
    state: TypeState.Physical,
    stage: 4,
    base: "roseseed",
  },
  {
    name: "Red Rose Blossom",
    icons: ["redroseblossom"],
    id: "redroseblossom",
    munzee_id: 1786,
    state: TypeState.Physical,
    stage: 5,
    base: "roseseed",
  },
  {
    name: "Violet Rose Blossom",
    icons: ["violetroseblossom"],
    id: "violetroseblossom",
    munzee_id: 1787,
    state: TypeState.Physical,
    stage: 5,
    base: "roseseed",
  },
  {
    name: "White Rose Blossom",
    icons: ["whiteroseblossom"],
    id: "whiteroseblossom",
    munzee_id: 1788,
    state: TypeState.Physical,
    stage: 5,
    base: "roseseed",
  },
  {
    name: "Yellow Rose Blossom",
    icons: ["yellowroseblossom"],
    id: "yellowroseblossom",
    munzee_id: 1789,
    state: TypeState.Physical,
    stage: 5,
    base: "roseseed",
  },
  {
    name: "Lily Seed",
    icons: ["lilyseed"],
    id: "lilyseed",
    munzee_id: 1790,
    state: TypeState.Physical,
    stage: 1,
    base: "lilyseed",
  },
  {
    name: "Lily Germination",
    icons: ["lilygermination"],
    id: "lilygermination",
    munzee_id: 1791,
    state: TypeState.Physical,
    stage: 2,
    base: "lilyseed",
  },
  {
    name: "Lily Growth",
    icons: ["lilygrowth"],
    id: "lilygrowth",
    munzee_id: 1792,
    state: TypeState.Physical,
    stage: 3,
    base: "lilyseed",
  },
  {
    name: "Lily Bud",
    icons: ["lilybud"],
    id: "lilybud",
    munzee_id: 1793,
    state: TypeState.Physical,
    stage: 4,
    base: "lilyseed",
  },
  {
    name: "Pink Lily Blossom",
    icons: ["pinklilyblossom"],
    id: "pinklilyblossom",
    munzee_id: 1794,
    state: TypeState.Physical,
    stage: 5,
    base: "lilyseed",
  },
  {
    name: "Violet Lily Blossom",
    icons: ["violetlilyblossom"],
    id: "violetlilyblossom",
    munzee_id: 1795,
    state: TypeState.Physical,
    stage: 5,
    base: "lilyseed",
  },
  {
    name: "White Lily Blossom",
    icons: ["whitelilyblossom"],
    id: "whitelilyblossom",
    munzee_id: 1796,
    state: TypeState.Physical,
    stage: 5,
    base: "lilyseed",
  },
  {
    name: "Carnation",
    icons: ["carnation"],
    id: "carnation",
    munzee_id: 1797,
    state: TypeState.Virtual,
    stage: 5,
    base: "carnationseed",
    hidden: [TypeHidden.All],
  },
  {
    name: "Carnation Seed",
    icons: ["carnationseed"],
    id: "carnationseed",
    munzee_id: 1798,
    state: TypeState.Virtual,
    stage: 1,
    base: "carnationseed",
    hidden: [TypeHidden.Deploy],
  },
  {
    name: "Carnation Germination",
    icons: ["carnationgermination"],
    id: "carnationgermination",
    munzee_id: 1799,
    state: TypeState.Virtual,
    stage: 2,
    base: "carnationseed",
  },
  {
    name: "Carnation Growth",
    icons: ["carnationgrowth"],
    id: "carnationgrowth",
    munzee_id: 1800,
    state: TypeState.Virtual,
    stage: 3,
    base: "carnationseed",
  },
  {
    name: "Carnation Bud",
    icons: ["carnationbud"],
    id: "carnationbud",
    munzee_id: 1801,
    state: TypeState.Virtual,
    stage: 4,
    base: "carnationseed",
  },
  {
    name: "Pink Carnation Blossom",
    icons: ["pinkcarnationblossom"],
    id: "pinkcarnationblossom",
    munzee_id: 1802,
    state: TypeState.Virtual,
    stage: 5,
    base: "carnationseed",
  },
  {
    name: "Red Carnation Blossom",
    icons: ["redcarnationblossom"],
    id: "redcarnationblossom",
    munzee_id: 1803,
    state: TypeState.Virtual,
    stage: 5,
    base: "carnationseed",
  },
  {
    name: "Violet Carnation Blossom",
    icons: ["violetcarnationblossom"],
    id: "violetcarnationblossom",
    munzee_id: 1804,
    state: TypeState.Virtual,
    stage: 5,
    base: "carnationseed",
  },
  {
    name: "White Carnation Blossom",
    icons: ["whitecarnationblossom"],
    id: "whitecarnationblossom",
    munzee_id: 1805,
    state: TypeState.Virtual,
    stage: 5,
    base: "carnationseed",
  },
  {
    name: "Yellow Carnation Blossom",
    icons: ["yellowcarnationblossom"],
    id: "yellowcarnationblossom",
    munzee_id: 1806,
    state: TypeState.Virtual,
    stage: 5,
    base: "carnationseed",
  },

  // Butterfly
  {
    name: "Butterfly Egg",
    icons: ["butterflyegg"],
    id: "butterflyegg",
    munzee_id: 1836,
    state: TypeState.Physical,
    stage: 1,
    base: "butterflyegg",
  },
  {
    name: "Caterpillar",
    icons: ["caterpillar"],
    id: "caterpillar",
    munzee_id: 1837,
    state: TypeState.Physical,
    stage: 2,
    base: "butterflyegg",
  },
  {
    name: "Chrysalis",
    icons: ["chrysalis"],
    id: "chrysalis",
    munzee_id: 1838,
    state: TypeState.Physical,
    stage: 3,
    base: "butterflyegg",
  },
  {
    name: "Hatched Chrysalis",
    icons: ["hatchedchrysalis"],
    id: "hatchedchrysalis",
    munzee_id: 1839,
    state: TypeState.Physical,
    stage: 4,
    base: "butterflyegg",
  },
  {
    name: "Butterfly",
    icons: ["butterfly"],
    id: "butterfly",
    munzee_id: 1830,
    state: TypeState.Bouncer,
    lands_on: [
      "skyland",
      "farmer",
      "farmerandwife",
      "family",
      "pottedplant",
      "garden",
      "field",
      "peasplant",
      "carrotplant",
      "goldencarrotplant",
      "tomatoplant",
      "cornstalk",
      type =>
        ["tulipseed", "roseseed", "carnationseed", "lilyseed"].includes(
          type.meta.evolution_base || ""
        ) && (type.meta.evolution_stage || 0) >= 3,
      type => type.has_tag(TypeTags.TypeSeasonal),
      "trail",
      "munzee",
      "virtual_rainbow",
    ],
    stage: 5,
    base: "butterflyegg",
    hidden: [TypeHidden.Capture, TypeHidden.Deploy, TypeHidden.Bouncers],
  },
  {
    name: "Morpho Butterfly",
    icons: ["morphobutterfly"],
    id: "morphobutterfly",
    munzee_id: 1840,
    state: TypeState.Bouncer,
    lands_on: [
      "skyland",
      "farmer",
      "farmerandwife",
      "family",
      "pottedplant",
      "garden",
      "field",
      "peasplant",
      "carrotplant",
      "goldencarrotplant",
      "tomatoplant",
      "cornstalk",
      type =>
        ["tulipseed", "roseseed", "carnationseed", "lilyseed"].includes(
          type.meta.evolution_base || ""
        ) && (type.meta.evolution_stage || 0) >= 3,
      type => type.has_tag(TypeTags.TypeSeasonal),
      "trail",
      "munzee",
      "virtual_rainbow",
    ],
    stage: 5,
    base: "butterflyegg",
  },
  {
    name: "Monarch Butterfly",
    icons: ["monarchbutterfly"],
    id: "monarchbutterfly",
    munzee_id: 1841,
    state: TypeState.Bouncer,
    lands_on: [
      "skyland",
      "farmer",
      "farmerandwife",
      "family",
      "pottedplant",
      "garden",
      "field",
      "peasplant",
      "carrotplant",
      "goldencarrotplant",
      "tomatoplant",
      "cornstalk",
      type =>
        ["tulipseed", "roseseed", "carnationseed", "lilyseed"].includes(
          type.meta.evolution_base || ""
        ) && (type.meta.evolution_stage || 0) >= 3,
      type => type.has_tag(TypeTags.TypeSeasonal),
      "trail",
      "munzee",
      "virtual_rainbow",
    ],
    stage: 5,
    base: "butterflyegg",
  },
  {
    name: "Lime Butterfly",
    icons: ["limebutterfly"],
    id: "limebutterfly",
    munzee_id: 1842,
    state: TypeState.Bouncer,
    lands_on: [
      "skyland",
      "farmer",
      "farmerandwife",
      "family",
      "pottedplant",
      "garden",
      "field",
      "peasplant",
      "carrotplant",
      "goldencarrotplant",
      "tomatoplant",
      "cornstalk",
      type =>
        ["tulipseed", "roseseed", "carnationseed", "lilyseed"].includes(
          type.meta.evolution_base || ""
        ) && (type.meta.evolution_stage || 0) >= 3,
      type => type.has_tag(TypeTags.TypeSeasonal),
      "trail",
      "munzee",
      "virtual_rainbow",
    ],
    stage: 5,
    base: "butterflyegg",
  },

  // Frog
  {
    name: "Frog Egg",
    icons: ["frogegg"],
    id: "frogegg",
    munzee_id: 2106,
    state: TypeState.Physical,
    stage: 1,
    base: "frogegg",
  },
  {
    name: "Tadpole",
    icons: ["tadpole"],
    id: "tadpole",
    munzee_id: 2107,
    state: TypeState.Physical,
    stage: 2,
    base: "frogegg",
  },
  {
    name: "Pollywog",
    icons: ["pollywog"],
    id: "pollywog",
    munzee_id: 2108,
    state: TypeState.Physical,
    stage: 3,
    base: "frogegg",
  },
  {
    name: "Froglet",
    icons: ["froglet"],
    id: "froglet",
    munzee_id: 2109,
    state: TypeState.Physical,
    stage: 4,
    base: "frogegg",
  },
  {
    name: "Frog",
    icons: ["frog"],
    id: "frog",
    munzee_id: 2067,
    state: TypeState.Bouncer,
    lands_on: [
      "musclecar",
      type =>
        ["seaweed", "canoe", "safaritruck"].includes(type.meta.evolution_base || "") &&
        (type.meta.evolution_stage || 0) >= 3,
      "earthmystery",
      "watermystery",
      "trail",
      "munzee",
      type => type.has_tag(TypeTags.VirtualColourGreen),
    ],
    stage: 5,
    base: "frogegg",
    hidden: [TypeHidden.Capture, TypeHidden.Deploy, TypeHidden.Bouncers],
  },
  {
    name: "Tree Frog",
    icons: ["treefrog"],
    id: "treefrog",
    munzee_id: 2110,
    state: TypeState.Bouncer,
    lands_on: [
      "skyland",
      "musclecar",
      type =>
        ["seaweed", "canoe", "safaritruck"].includes(type.meta.evolution_base || "") &&
        (type.meta.evolution_stage || 0) >= 3,
      "earthmystery",
      "watermystery",
      "trail",
      "munzee",
      type => type.has_tag(TypeTags.VirtualColourGreen),
    ],
    stage: 5,
    base: "frogegg",
  },
  {
    name: "Poison Dart Frog",
    icons: ["poisondartfrog"],
    id: "poisondartfrog",
    munzee_id: 2111,
    state: TypeState.Bouncer,
    lands_on: [
      "skyland",
      "musclecar",
      type =>
        ["seaweed", "canoe", "safaritruck"].includes(type.meta.evolution_base || "") &&
        (type.meta.evolution_stage || 0) >= 3,
      "earthmystery",
      "watermystery",
      "trail",
      "munzee",
      type => type.has_tag(TypeTags.VirtualColourGreen),
    ],
    stage: 5,
    base: "frogegg",
  },
  {
    name: "Tomato Frog",
    icons: ["tomatofrog"],
    id: "tomatofrog",
    munzee_id: 2112,
    state: TypeState.Bouncer,
    lands_on: [
      "skyland",
      "musclecar",
      type =>
        ["seaweed", "canoe", "safaritruck"].includes(type.meta.evolution_base || "") &&
        (type.meta.evolution_stage || 0) >= 3,
      "earthmystery",
      "watermystery",
      "trail",
      "munzee",
      type => type.has_tag(TypeTags.VirtualColourGreen),
    ],
    stage: 5,
    base: "frogegg",
  },

  // Jellyfish
  {
    name: "Planula Larva",
    icons: ["planulalarva"],
    id: "planulalarva",
    munzee_id: 2461,
    state: TypeState.Virtual,
    stage: 1,
    base: "planulalarva",
    hidden: [],
  },
  {
    name: "Polyp",
    icons: ["polyp"],
    id: "polyp",
    munzee_id: 2462,
    state: TypeState.Virtual,
    stage: 2,
    base: "planulalarva",
  },
  {
    name: "Polyp with Bulbs",
    icons: ["polypwithbulbs"],
    id: "polypwithbulbs",
    munzee_id: 2463,
    state: TypeState.Virtual,
    stage: 3,
    base: "planulalarva",
  },
  {
    name: "Ephyra Larva",
    icons: ["ephyralarva"],
    id: "ephyralarva",
    munzee_id: 2464,
    state: TypeState.Virtual,
    stage: 4,
    base: "planulalarva",
  },
  {
    name: "Jellyfish",
    icons: ["jellyfish"],
    id: "jellyfish",
    state: TypeState.Bouncer,
    lands_on: [
      "treehouse",
      "skyland",
      type => ["seaweed", "canoe", "safaritruck"].includes(type.meta.evolution_base || ""),
      "earthmystery",
      "watermystery",
      "munzee",
      type => type.has_tag(TypeTags.VirtualColourGreen),
    ],
    stage: 5,
    base: "planulalarva",
    hidden: [TypeHidden.Capture, TypeHidden.Deploy, TypeHidden.Inventory, TypeHidden.Bouncers],
  },
  {
    name: "Box Jellyfish",
    icons: ["boxjellyfish"],
    id: "boxjellyfish",
    munzee_id: 2466,
    state: TypeState.Bouncer,
    lands_on: [
      "treehouse",
      "skyland",
      type => ["seaweed", "canoe", "safaritruck"].includes(type.meta.evolution_base || ""),
      "earthmystery",
      "watermystery",
      "munzee",
      type => type.has_tag(TypeTags.VirtualColourGreen),
    ],
    stage: 5,
    base: "planulalarva",
  },
  {
    name: "Golden Jellyfish",
    icons: ["goldenjellyfish"],
    id: "goldenjellyfish",
    munzee_id: 2467,
    state: TypeState.Bouncer,
    lands_on: [
      "treehouse",
      "skyland",
      type => ["seaweed", "canoe", "safaritruck"].includes(type.meta.evolution_base || ""),
      "earthmystery",
      "watermystery",
      "munzee",
      type => type.has_tag(TypeTags.VirtualColourGreen),
    ],
    stage: 5,
    base: "planulalarva",
  },
  {
    name: "PB & Jellyfish",
    icons: ["pb&jellyfish"],
    id: "pb&jellyfish",
    munzee_id: 2468,
    state: TypeState.Bouncer,
    lands_on: [
      "treehouse",
      "skyland",
      type => ["seaweed", "canoe", "safaritruck"].includes(type.meta.evolution_base || ""),
      "earthmystery",
      "watermystery",
      "munzee",
      type => type.has_tag(TypeTags.VirtualColourGreen),
    ],
    stage: 5,
    base: "planulalarva",
  },

  // Turtle
  {
    name: "Turtle Egg",
    icons: ["turtleegg"],
    id: "turtleegg",
    munzee_id: 2452,
    state: TypeState.Physical,
    stage: 1,
    base: "turtleegg",
  },
  {
    name: "Turtle Hatchling",
    icons: ["turtlehatchling"],
    id: "turtlehatchling",
    munzee_id: 2453,
    state: TypeState.Physical,
    stage: 2,
    base: "turtleegg",
  },
  {
    name: "Juvenile Turtle",
    icons: ["juvenileturtle"],
    id: "juvenileturtle",
    munzee_id: 2454,
    state: TypeState.Physical,
    stage: 3,
    base: "turtleegg",
  },
  {
    name: "Adult Turtle",
    icons: ["adultturtle"],
    id: "adultturtle",
    munzee_id: 2455,
    state: TypeState.Physical,
    stage: 4,
    base: "turtleegg",
  },
  {
    name: "Turtle",
    icons: ["turtle"],
    id: "turtle",
    state: TypeState.Bouncer,
    lands_on: [
      "treehouse",
      "skyland",
      type => ["seaweed", "canoe", "safaritruck"].includes(type.meta.evolution_base || ""),
      "earthmystery",
      "watermystery",
      "munzee",
      type => type.has_tag(TypeTags.VirtualColourGreen),
    ],
    stage: 5,
    base: "turtleegg",
    hidden: [TypeHidden.Capture, TypeHidden.Deploy, TypeHidden.Bouncers],
  },
  {
    name: "Sea Turtle",
    icons: ["seaturtle"],
    id: "seaturtle",
    munzee_id: 2476,
    state: TypeState.Bouncer,
    lands_on: [
      "treehouse",
      "skyland",
      type => ["seaweed", "canoe", "safaritruck"].includes(type.meta.evolution_base || ""),
      "earthmystery",
      "watermystery",
      "munzee",
      type => type.has_tag(TypeTags.VirtualColourGreen),
    ],
    stage: 5,
    base: "turtleegg",
  },
  {
    name: "Snapping Turtle",
    icons: ["snappingturtle"],
    id: "snappingturtle",
    munzee_id: 2457,
    state: TypeState.Bouncer,
    lands_on: [
      "treehouse",
      "skyland",
      type => ["seaweed", "canoe", "safaritruck"].includes(type.meta.evolution_base || ""),
      "earthmystery",
      "watermystery",
      "munzee",
      type => type.has_tag(TypeTags.VirtualColourGreen),
    ],
    stage: 5,
    base: "turtleegg",
  },
  {
    name: "Taekwondo Tortoise",
    icons: ["taekwondotortoise"],
    id: "taekwondotortoise",
    munzee_id: 2458,
    state: TypeState.Bouncer,
    lands_on: [
      "treehouse",
      "skyland",
      type => ["seaweed", "canoe", "safaritruck"].includes(type.meta.evolution_base || ""),
      "earthmystery",
      "watermystery",
      "munzee",
      type => type.has_tag(TypeTags.VirtualColourGreen),
    ],
    stage: 5,
    base: "turtleegg",
  },

  // Bee
  {
    name: "Bee Eggs",
    icons: ["beeeggs"],
    id: "beeeggs",
    state: TypeState.Physical,
    stage: 1,
    base: "beeeggs",
  },
  {
    name: "Bee Larvae",
    icons: ["beelarvae"],
    id: "beelarvae",
    state: TypeState.Physical,
    stage: 2,
    base: "beeeggs",
  },
  {
    name: "Bee Pupae",
    icons: ["beepupae"],
    id: "beepupae",
    state: TypeState.Physical,
    stage: 3,
    base: "beeeggs",
  },
  {
    name: "Empty Honeycomb",
    icons: ["emptyhoneycomb"],
    id: "emptyhoneycomb",
    state: TypeState.Physical,
    stage: 4,
    base: "beeeggs",
  },
  {
    name: "Bee",
    icons: ["bee"],
    id: "bee",
    state: TypeState.Bouncer,
    lands_on: [
      "treehouse",
      "skyland",
      type =>
        ["tulipseed", "roseseed", "lilyseed", "carnationseed"].includes(
          type.meta.evolution_base || ""
        ),
      "earthmystery",
      "munzee",
      type => type.has_tag(TypeTags.TypeVirtual),
    ],
    stage: 5,
    base: "beeeggs",
    hidden: [TypeHidden.Capture, TypeHidden.Deploy, TypeHidden.Bouncers],
  },
  {
    name: "Honey Bee",
    icons: ["honeybee"],
    id: "honeybee",
    state: TypeState.Bouncer,
    lands_on: [
      "treehouse",
      "skyland",
      type =>
        ["tulipseed", "roseseed", "lilyseed", "carnationseed"].includes(
          type.meta.evolution_base || ""
        ),
      "earthmystery",
      "munzee",
      type => type.has_tag(TypeTags.TypeVirtual),
    ],
    stage: 5,
    base: "beeeggs",
  },
  {
    name: "Queen Bee",
    icons: ["queenbee"],
    id: "queenbee",
    state: TypeState.Bouncer,
    lands_on: [
      "treehouse",
      "skyland",
      type =>
        ["tulipseed", "roseseed", "lilyseed", "carnationseed"].includes(
          type.meta.evolution_base || ""
        ),
      "earthmystery",
      "munzee",
      type => type.has_tag(TypeTags.TypeVirtual),
    ],
    stage: 5,
    base: "beeeggs",
  },
  {
    name: "WallaBee",
    icons: ["wallabee"],
    id: "wallabee",
    state: TypeState.Bouncer,
    lands_on: [
      "treehouse",
      "skyland",
      type =>
        ["tulipseed", "roseseed", "lilyseed", "carnationseed"].includes(
          type.meta.evolution_base || ""
        ),
      "earthmystery",
      "munzee",
      type => type.has_tag(TypeTags.TypeVirtual),
    ],
    stage: 5,
    base: "beeeggs",
  },
];

export default nature;