import { SeasonalCategory } from ".";

const s2018: SeasonalCategory[] = [
  {
    name: "Christmas 2018",
    id: "christmas2018",
    starts: "2018-00-00T00:00:00-05:00",
    ends: "2018-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Flat Santa",
        icons: ["flatsanta2018"],
        id: "flatsanta2018",
        munzee_id: 1656,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Rover Reindeer",
        icons: ["roverreindeer2018"],
        id: "roverreindeer2018",
        munzee_id: 1666,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Rudolph Reindeer",
        icons: ["rudolphreindeer2018"],
        id: "rudolphreindeer2018",
        munzee_id: 1665,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Dasher Reindeer",
        icons: ["dasherreindeer2018"],
        id: "dasherreindeer2018",
        munzee_id: 1657,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Dancer Reindeer",
        icons: ["dancerreindeer2018"],
        id: "dancerreindeer2018",
        munzee_id: 1658,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Prancer Reindeer",
        icons: ["prancerreindeer2018"],
        id: "prancerreindeer2018",
        munzee_id: 1659,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Vixen Reindeer",
        icons: ["vixenreindeer2018"],
        id: "vixenreindeer2018",
        munzee_id: 1660,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Comet Reindeer",
        icons: ["cometreindeer2018"],
        id: "cometreindeer2018",
        munzee_id: 1661,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Cupid Reindeer",
        icons: ["cupidreindeer2018"],
        id: "cupidreindeer2018",
        munzee_id: 1662,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Donner Reindeer",
        icons: ["donnerreindeer2018"],
        id: "donnerreindeer2018",
        munzee_id: 1663,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Blitzen Reindeer",
        icons: ["blitzenreindeer2018"],
        id: "blitzenreindeer2018",
        munzee_id: 1664,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Retro Logos",
    id: "retrologos2018",
    starts: "2018-00-00T00:00:00-05:00",
    ends: "2018-00-00T00:00:00-05:00",
    specials: [
      {
        name: "2018 Munzee Logo",
        icons: ["2018munzeelogo"],
        id: "2018munzeelogo",
        munzee_id: 1636,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "2015 Munzee Logo",
        icons: ["2015munzeelogo"],
        id: "2015munzeelogo",
        munzee_id: 1635,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "2014 Munzee Logo",
        icons: ["2014munzeelogo"],
        id: "2014munzeelogo",
        munzee_id: 1634,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "2013 Munzee Logo",
        icons: ["2013munzeelogo"],
        id: "2013munzeelogo",
        munzee_id: 1633,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "2011 Munzee Logo",
        icons: ["2011munzeelogo"],
        id: "2011munzeelogo",
        munzee_id: 1632,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Zombie Outbreak",
    id: "zombieoutbreak2018",
    starts: "2018-00-00T00:00:00-05:00",
    ends: "2018-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Zombie Outbreak",
        icons: ["zombieoutbreak2018"],
        id: "zombieoutbreak2018",
        munzee_id: 1589,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Talk like a Pirate Day 2018",
    id: "talklike a pirate day 20182018",
    starts: "2018-00-00T00:00:00-05:00",
    ends: "2018-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Cargo Ship",
        icons: ["cargoship"],
        id: "cargoship",
        munzee_id: 1526,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Treasure Ship",
        icons: ["treasureship"],
        id: "treasureship",
        munzee_id: 1527,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Ghost Ship",
        icons: ["ghostship"],
        id: "ghostship",
        munzee_id: 1528,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Bacon Day 2018",
    id: "baconday 20182018",
    starts: "2018-00-00T00:00:00-05:00",
    ends: "2018-00-00T00:00:00-05:00",
    specials: [
      {
        name: "American Bacon",
        icons: ["americanbacon"],
        id: "americanbacon",
        munzee_id: 1523,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "International Bacon",
        icons: ["internationalbacon"],
        id: "internationalbacon",
        munzee_id: 1524,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Flying Pig",
        icons: ["flyingpig"],
        id: "flyingpig",
        munzee_id: 1522,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "World Photo Day",
    id: "worldphoto day2018",
    starts: "2018-00-00T00:00:00-05:00",
    ends: "2018-00-00T00:00:00-05:00",
    specials: [
      {
        name: "World Photo Day",
        icons: ["worldphotoday2018"],
        id: "worldphotoday2018",
        munzee_id: 1519,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "7th Birthday Clowns",
    id: "7thbirthday clowns2018",
    starts: "2018-00-00T00:00:00-05:00",
    ends: "2018-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Clown Car",
        icons: ["clowncar2018"],
        id: "clowncar2018",
        munzee_id: 1387,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Party Clown",
        icons: ["partyclown2018"],
        id: "partyclown2018",
        munzee_id: 1390,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Rodeo Clown",
        icons: ["rodeoclown2018"],
        id: "rodeoclown2018",
        munzee_id: 1392,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Harlequin Clown",
        icons: ["harlequinclown2018"],
        id: "harlequinclown2018",
        munzee_id: 1391,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Tramp Clown",
        icons: ["trampclown2018"],
        id: "trampclown2018",
        munzee_id: 1389,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Mime",
        icons: ["mime2018"],
        id: "mime2018",
        munzee_id: 1388,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Sad Clown",
        icons: ["sadclown2018"],
        id: "sadclown2018",
        munzee_id: 1394,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Scary Clown",
        icons: ["scaryclown2018"],
        id: "scaryclown2018",
        munzee_id: 1393,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "International Yoga Day",
    id: "internationalyoga day2018",
    starts: "2018-00-00T00:00:00-05:00",
    ends: "2018-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Cobra Yoga Pose",
        icons: ["cobrayogapose"],
        id: "cobrayogapose",
        munzee_id: 1374,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Downward Dog Yoga Pose",
        icons: ["downwarddogyogapose"],
        id: "downwarddogyogapose",
        munzee_id: 1375,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Lotus Yoga Pose",
        icons: ["lotusyogapose"],
        id: "lotusyogapose",
        munzee_id: 1376,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Warrior II Yoga Pose",
        icons: ["warrioriiyogapose"],
        id: "warrioriiyogapose",
        munzee_id: 1377,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Towel Day 2018",
    id: "towelday 20182018",
    starts: "2018-00-00T00:00:00-05:00",
    ends: "2018-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Hitchhiker",
        icons: ["hitchhiker2018"],
        id: "hitchhiker2018",
        munzee_id: 1352,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Towel Day 2018",
        icons: ["towelday2018"],
        id: "towelday2018",
        munzee_id: 1351,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Flat Day the 13th Part II",
    id: "flatday the 13th part ii2018",
    starts: "2018-00-00T00:00:00-05:00",
    ends: "2018-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Meanie",
        icons: ["meanie"],
        id: "meanie",
        munzee_id: 1320,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Masked Flat Matt",
        icons: ["maskedflatmatt"],
        id: "maskedflatmatt",
        munzee_id: 1319,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Pi Day 2018",
    id: "piday 20182018",
    starts: "2018-00-00T00:00:00-05:00",
    ends: "2018-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Pi Day 2018",
        icons: ["piday2018"],
        id: "piday2018",
        munzee_id: 1259,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Valentine's Day 2018",
    id: "valentines day 20182018",
    starts: "2018-00-00T00:00:00-05:00",
    ends: "2018-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Heart Capper 1",
        icons: ["heartcapper1"],
        id: "heartcapper1",
        munzee_id: 1235,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Heart Capper 2",
        icons: ["heartcapper2"],
        id: "heartcapper2",
        munzee_id: 1236,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Heart Wrangler 1",
        icons: ["heartwrangler1"],
        id: "heartwrangler1",
        munzee_id: 1233,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Heart Wrangler 2",
        icons: ["heartwrangler2"],
        id: "heartwrangler2",
        munzee_id: 1234,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "International Thank You Day",
    id: "internationalthank you day2018",
    starts: "2018-00-00T00:00:00-05:00",
    ends: "2018-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Thank you from Rob",
        icons: ["thankyoufromrob2018"],
        id: "thankyoufromrob2018",
        munzee_id: 1219,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Thank you from Matt",
        icons: ["thankyoufrommatt2018"],
        id: "thankyoufrommatt2018",
        munzee_id: 1220,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Thank you from Louise",
        icons: ["thankyoufromlouise2018"],
        id: "thankyoufromlouise2018",
        munzee_id: 1218,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
];

export default s2018;