import { SeasonalCategory } from ".";

const s2019: SeasonalCategory[] = [
  {
    name: "Global Grub",
    id: "globalgrub2019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Switzerland Global Grub",
        icons: ["switzerlandglobalgrub"],
        id: "switzerlandglobalgrub",
        munzee_id: 1724,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Australia Global Grub",
        icons: ["australiaglobalgrub"],
        id: "australiaglobalgrub",
        munzee_id: 1725,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "China Global Grub",
        icons: ["chinaglobalgrub"],
        id: "chinaglobalgrub",
        munzee_id: 1726,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "France Global Grub",
        icons: ["franceglobalgrub"],
        id: "franceglobalgrub",
        munzee_id: 1727,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Greece Global Grub",
        icons: ["greeceglobalgrub"],
        id: "greeceglobalgrub",
        munzee_id: 1728,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Japan Global Grub",
        icons: ["japanglobalgrub"],
        id: "japanglobalgrub",
        munzee_id: 1729,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Thailand Global Grub",
        icons: ["thailandglobalgrub"],
        id: "thailandglobalgrub",
        munzee_id: 1730,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Mexico Global Grub",
        icons: ["mexicoglobalgrub"],
        id: "mexicoglobalgrub",
        munzee_id: 1731,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Korea Global Grub",
        icons: ["koreaglobalgrub"],
        id: "koreaglobalgrub",
        munzee_id: 1732,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Sweden Global Grub",
        icons: ["swedenglobalgrub"],
        id: "swedenglobalgrub",
        munzee_id: 1733,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Italy Global Grub",
        icons: ["italyglobalgrub"],
        id: "italyglobalgrub",
        munzee_id: 1734,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "USA Global Grub",
        icons: ["usaglobalgrub"],
        id: "usaglobalgrub",
        munzee_id: 1735,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Pakistan Global Grub",
        icons: ["pakistanglobalgrub"],
        id: "pakistanglobalgrub",
        munzee_id: 1736,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Ukraine Global Grub",
        icons: ["ukraineglobalgrub"],
        id: "ukraineglobalgrub",
        munzee_id: 1737,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Spain Global Grub",
        icons: ["spainglobalgrub"],
        id: "spainglobalgrub",
        munzee_id: 1738,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Montenegro Global Grub",
        icons: ["montenegroglobalgrub"],
        id: "montenegroglobalgrub",
        munzee_id: 1739,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "India Global Grub",
        icons: ["indiaglobalgrub"],
        id: "indiaglobalgrub",
        munzee_id: 1740,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Portugal Global Grub",
        icons: ["portugalglobalgrub"],
        id: "portugalglobalgrub",
        munzee_id: 1741,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Philippines Global Grub",
        icons: ["philippinesglobalgrub"],
        id: "philippinesglobalgrub",
        munzee_id: 1742,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Vietnam Global Grub",
        icons: ["vietnamglobalgrub"],
        id: "vietnamglobalgrub",
        munzee_id: 1743,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Christmas 2019",
    id: "christmas20192019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Kringle's Cowboy Hat",
        icons: ["kringle'scowboyhat"],
        id: "kringle'scowboyhat",
        munzee_id: 2309,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Lone Star Tree Topper",
        icons: ["lonestartreetopper"],
        id: "lonestartreetopper",
        munzee_id: 2310,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Silver Spurs",
        icons: ["silverspurs"],
        id: "silverspurs",
        munzee_id: 2311,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Christmas Cactus",
        icons: ["christmascactus"],
        id: "christmascactus",
        munzee_id: 2312,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Boot Scootin' Stocking",
        icons: ["bootscootin'stocking"],
        id: "bootscootin'stocking",
        munzee_id: 2313,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "State Shaped Ornament",
        icons: ["stateshapedornament"],
        id: "stateshapedornament",
        munzee_id: 2314,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Can o' Fake Snow",
        icons: ["cano'fakesnow"],
        id: "cano'fakesnow",
        munzee_id: 2315,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Festive Football",
        icons: ["festivefootball"],
        id: "festivefootball",
        munzee_id: 2316,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Gingerbread Barn",
        icons: ["gingerbreadbarn"],
        id: "gingerbreadbarn",
        munzee_id: 2317,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Bluebonnet Mistletoe",
        icons: ["bluebonnetmistletoe"],
        id: "bluebonnetmistletoe",
        munzee_id: 2318,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Santa's Saddle",
        icons: ["santa'ssaddle"],
        id: "santa'ssaddle",
        munzee_id: 2319,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Nacogdoches Nutcracker",
        icons: ["nacogdochesnutcracker"],
        id: "nacogdochesnutcracker",
        munzee_id: 2320,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Ninja-Bread Men 2019",
    id: "ninjabread men 20192019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Shuriken Ninja-Bread Man",
        icons: ["shurikenninja-breadman"],
        id: "shurikenninja-breadman",
        munzee_id: 2259,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Sai Ninja-Bread Man",
        icons: ["saininja-breadman"],
        id: "saininja-breadman",
        munzee_id: 2258,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Nunchuck Ninja-Bread Man",
        icons: ["nunchuckninja-breadman"],
        id: "nunchuckninja-breadman",
        munzee_id: 2257,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Katana Ninja-Bread Man",
        icons: ["katananinja-breadman"],
        id: "katananinja-breadman",
        munzee_id: 2256,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Origami Day 2019",
    id: "origamiday 20192019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Origami Boat",
        icons: ["origamiboat"],
        id: "origamiboat",
        munzee_id: 2248,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Origami Butterfly",
        icons: ["origamibutterfly"],
        id: "origamibutterfly",
        munzee_id: 2249,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Origami Crane",
        icons: ["origamicrane"],
        id: "origamicrane",
        munzee_id: 2246,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Origami Lily",
        icons: ["origamilily"],
        id: "origamilily",
        munzee_id: 2247,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "MH-Qlue",
    id: "mhqlue2019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "MH-Qlue",
        icons: ["mh-qlue"],
        id: "mh-qlue",
        munzee_id: 2209,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "University Professor Corn",
        icons: ["universityprofessorcorn"],
        id: "universityprofessorcorn",
        munzee_id: 2213,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Mister Zee",
        icons: ["misterzee"],
        id: "misterzee",
        munzee_id: 2214,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Mademoiselle Eventa",
        icons: ["mademoiselleeventa"],
        id: "mademoiselleeventa",
        munzee_id: 2215,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "General Green E",
        icons: ["generalgreene"],
        id: "generalgreene",
        munzee_id: 2216,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Ban Hammer",
        icons: ["banhammercard"],
        id: "banhammercard",
        munzee_id: 2217,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "External Battery",
        icons: ["externalbatterycard"],
        id: "externalbatterycard",
        munzee_id: 2218,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Unicorn Horn",
        icons: ["unicornhorncard"],
        id: "unicornhorncard",
        munzee_id: 2219,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Globe",
        icons: ["globecard"],
        id: "globecard",
        munzee_id: 2220,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "The Production Room",
        icons: ["theproductionroom"],
        id: "theproductionroom",
        munzee_id: 2221,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "The Videocast Studio",
        icons: ["thevideocaststudio"],
        id: "thevideocaststudio",
        munzee_id: 2222,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "The Munzee Museum",
        icons: ["themunzeemuseum"],
        id: "themunzeemuseum",
        munzee_id: 2223,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "The CZeeO's Office",
        icons: ["theczeeo'soffice"],
        id: "theczeeo'soffice",
        munzee_id: 2224,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Monster Nomads",
    id: "monsternomads2019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Frankenstein Fingers",
        icons: ["frankenstein'shand"],
        id: "frankenstein'shand",
        munzee_id: 2230,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Werewolf paw",
        icons: ["werewolfpaw"],
        id: "werewolfpaw",
        munzee_id: 2229,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Mummy Mitt",
        icons: ["mummyhand"],
        id: "mummyhand",
        munzee_id: 2228,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Knight's Armor",
    id: "knights armor2019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Knight's Helmet",
        icons: ["knight'shelmet2019"],
        id: "knight'shelmet2019",
        munzee_id: 2139,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Knight's Right Gauntlet",
        icons: ["knight'srightgauntlet2019"],
        id: "knight'srightgauntlet2019",
        munzee_id: 2141,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Knight's Left Gauntlet",
        icons: ["knight'sleftgauntlet2019"],
        id: "knight'sleftgauntlet2019",
        munzee_id: 2140,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Knight's Breastplate",
        icons: ["knight'sbreastplate2019"],
        id: "knight'sbreastplate2019",
        munzee_id: 2142,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Knight's Left Boot",
        icons: ["knight'sleftboot2019"],
        id: "knight'sleftboot2019",
        munzee_id: 2143,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Knight's Right Boot",
        icons: ["knight'srightboot2019"],
        id: "knight'srightboot2019",
        munzee_id: 2144,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Teeth",
    id: "teeth2019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "White Tooth",
        icons: ["whitetooth2019"],
        id: "whitetooth2019",
        munzee_id: 2124,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Gold Tooth",
        icons: ["goldtooth2019"],
        id: "goldtooth2019",
        munzee_id: 2125,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Diamond Tooth",
        icons: ["diamondtooth2019"],
        id: "diamondtooth2019",
        munzee_id: 2126,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "She Said YES",
    id: "shesaid yes2019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "She Said YES - Physical",
        icons: ["shesaidyes-physical"],
        id: "shesaidyes-physical",
        munzee_id: 2121,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "She Said YES - Virtual",
        icons: ["shesaidyes-virtual"],
        id: "shesaidyes-virtual",
        munzee_id: 2122,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "8 Mate",
    id: "8mate2019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "8 Mate",
        icons: ["8mate"],
        id: "8mate",
        munzee_id: 2073,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Flat Shuttle",
    id: "flatshuttle2019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Flat Shuttle",
        icons: ["flatshuttle"],
        id: "flatshuttle",
        munzee_id: 2068,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Flat Flyby Rob",
        icons: ["flatflybyrob"],
        id: "flatflybyrob",
        munzee_id: 2069,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Flat Flyby Matt",
        icons: ["flatflybymatt"],
        id: "flatflybymatt",
        munzee_id: 2070,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Flat Flyby Lou",
        icons: ["flatflybylou"],
        id: "flatflybylou",
        munzee_id: 2071,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Flat Flyby Hammock",
        icons: ["flatflybyhammock"],
        id: "flatflybyhammock",
        munzee_id: 2072,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Magic 8 Ball",
    id: "magic8 ball2019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Magic 8 Ball - ???\\U00BF??",
        icons: ["magic8ball-???u00bf??"],
        id: "magic8ball-???u00bf??",
        munzee_id: 2014,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Magic 8 Ball - Expect the Unexpected!",
        icons: ["magic8ball-expecttheunexpected!"],
        id: "magic8ball-expecttheunexpected!",
        munzee_id: 2013,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Magic 8 Ball - Grow the Map!",
        icons: ["magic8ball-growthemap!"],
        id: "magic8ball-growthemap!",
        munzee_id: 2015,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Magic 8 Ball - Nope",
        icons: ["magic8ball-nope"],
        id: "magic8ball-nope",
        munzee_id: 2016,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Magic 8 Ball - 1000 Hours",
        icons: ["magic8ball-1000hours"],
        id: "magic8ball-1000hours",
        munzee_id: 2018,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Magic 8 Ball - This is fine",
        icons: ["magic8ball-thisisfine"],
        id: "magic8ball-thisisfine",
        munzee_id: 2017,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Magic 8 Ball - Ask Rob",
        icons: ["magic8ball-askrob"],
        id: "magic8ball-askrob",
        munzee_id: 2011,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Magic 8 Ball - Blame Scott",
        icons: ["magic8ball-blamescott"],
        id: "magic8ball-blamescott",
        munzee_id: 2012,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Coupe du Munzee",
    id: "coupedu munzee2019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Argentina Coupe du Munzee",
        icons: ["argentinacoupedumunzee"],
        id: "argentinacoupedumunzee",
        munzee_id: 1962,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Australia Coupe du Munzee",
        icons: ["australiacoupedumunzee"],
        id: "australiacoupedumunzee",
        munzee_id: 1958,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Brazil Coupe du Munzee",
        icons: ["brazilcoupedumunzee"],
        id: "brazilcoupedumunzee",
        munzee_id: 1959,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Cameroon Coupe du Munzee",
        icons: ["camerooncoupedumunzee"],
        id: "camerooncoupedumunzee",
        munzee_id: 1966,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Canada Coupe du Munzee",
        icons: ["canadacoupedumunzee"],
        id: "canadacoupedumunzee",
        munzee_id: 1967,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Chile Coupe du Munzee",
        icons: ["chilecoupedumunzee"],
        id: "chilecoupedumunzee",
        munzee_id: 1970,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "China PR Coupe du Munzee",
        icons: ["chinaprcoupedumunzee"],
        id: "chinaprcoupedumunzee",
        munzee_id: 1954,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "England Coupe du Munzee",
        icons: ["englandcoupedumunzee"],
        id: "englandcoupedumunzee",
        munzee_id: 1963,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "France Coupe du Munzee",
        icons: ["francecoupedumunzee"],
        id: "francecoupedumunzee",
        munzee_id: 1950,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Germany Coupe du Munzee",
        icons: ["germanycoupedumunzee"],
        id: "germanycoupedumunzee",
        munzee_id: 1955,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Italy Coupe du Munzee",
        icons: ["italycoupedumunzee"],
        id: "italycoupedumunzee",
        munzee_id: 1960,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Jamaica Coupe du Munzee",
        icons: ["jamaicacoupedumunzee"],
        id: "jamaicacoupedumunzee",
        munzee_id: 1961,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Japan Coupe du Munzee",
        icons: ["japancoupedumunzee"],
        id: "japancoupedumunzee",
        munzee_id: 1964,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Netherlands Coupe du Munzee",
        icons: ["netherlandscoupedumunzee"],
        id: "netherlandscoupedumunzee",
        munzee_id: 1968,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "New Zealand Coupe du Munzee",
        icons: ["newzealandcoupedumunzee"],
        id: "newzealandcoupedumunzee",
        munzee_id: 1969,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Nigeria Coupe du Munzee",
        icons: ["nigeriacoupedumunzee"],
        id: "nigeriacoupedumunzee",
        munzee_id: 1951,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Noway Coupe du Munzee",
        icons: ["norwaycoupedumunzee"],
        id: "norwaycoupedumunzee",
        munzee_id: 1952,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Thailand Coupe du Munzee",
        icons: ["thailandcoupedumunzee"],
        id: "thailandcoupedumunzee",
        munzee_id: 1972,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Scotland Coupe du Munzee",
        icons: ["scotlandcoupedumunzee"],
        id: "scotlandcoupedumunzee",
        munzee_id: 1965,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "South Africa Coupe du Munzee",
        icons: ["southafricacoupedumunzee"],
        id: "southafricacoupedumunzee",
        munzee_id: 1956,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "South Korea Coupe du Munzee",
        icons: ["southkoreacoupedumunzee"],
        id: "southkoreacoupedumunzee",
        munzee_id: 1953,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Spain Coupe du Munzee",
        icons: ["spaincoupedumunzee"],
        id: "spaincoupedumunzee",
        munzee_id: 1957,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Sweden Coupe du Munzee",
        icons: ["swedencoupedumunzee"],
        id: "swedencoupedumunzee",
        munzee_id: 1971,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "United States Coupe du Munzee",
        icons: ["unitedstatescoupedumunzee"],
        id: "unitedstatescoupedumunzee",
        munzee_id: 1973,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Scavenger Hunt Day",
    id: "scavengerhunt day2019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Scavenger Hunt Day Compass",
        icons: ["scavengerhuntdaycompass"],
        id: "scavengerhuntdaycompass",
        munzee_id: 1942,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Scavenger Hunt Day Telescope",
        icons: ["scavengerhuntdaytelescope"],
        id: "scavengerhuntdaytelescope",
        munzee_id: 1943,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Scavenger Hunt Day Magnifying Glass",
        icons: ["scavengerhuntdaymagnifyingglass"],
        id: "scavengerhuntdaymagnifyingglass",
        munzee_id: 1944,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Scavenger Hunt Day Shovel",
        icons: ["scavengerhuntdayshovel"],
        id: "scavengerhuntdayshovel",
        munzee_id: 1945,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "PinPoints",
    id: "pinpoints2019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "PinPoints Physical",
        icons: ["pinpointsphysical"],
        id: "pinpointsphysical",
        munzee_id: 1928,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "PinPoints Virtual",
        icons: ["pinpointsvirtual"],
        id: "pinpointsvirtual",
        munzee_id: 1927,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Alien Day Invasion",
    id: "alienday invasion2019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "UFO",
        icons: ["ufo"],
        id: "ufo",
        munzee_id: 1917,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "UFO Virtual",
        icons: ["ufovirtual"],
        id: "ufovirtual",
        munzee_id: 1918,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Alien Egg",
        icons: ["alienegg"],
        id: "alienegg",
        munzee_id: 1915,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Alien Potato",
        icons: ["alienpotato"],
        id: "alienpotato",
        munzee_id: 1916,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Zeester Eggs",
    id: "zeestereggs2019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "White Egg",
        icons: ["whiteegg"],
        id: "whiteegg",
        munzee_id: 1890,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Blue Egg",
        icons: ["blueegg"],
        id: "blueegg",
        munzee_id: 1891,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Red Egg",
        icons: ["redegg"],
        id: "redegg",
        munzee_id: 1892,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Yellow Egg",
        icons: ["yellowegg"],
        id: "yellowegg",
        munzee_id: 1893,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Hatched White Egg",
        icons: ["hatchedwhiteegg"],
        id: "hatchedwhiteegg",
        munzee_id: 1894,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Hatched Blue Egg",
        icons: ["hatchedblueegg"],
        id: "hatchedblueegg",
        munzee_id: 1895,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Hatched Red Egg",
        icons: ["hatchedredegg"],
        id: "hatchedredegg",
        munzee_id: 1896,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Hatched Yellow Egg",
        icons: ["hatchedyellowegg"],
        id: "hatchedyellowegg",
        munzee_id: 1897,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Benson",
    id: "benson2019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Bouncing Benson",
        icons: ["bouncingbenson"],
        id: "bouncingbenson",
        munzee_id: 1847,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Floating Benson",
        icons: ["floatingbenson"],
        id: "floatingbenson",
        munzee_id: 1848,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "April Fools' Day 2019",
    id: "aprilfools' day 20192019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Flat Fish",
        icons: ["flatfish"],
        id: "flatfish",
        munzee_id: 1845,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Red Herring",
        icons: ["redherring"],
        id: "redherring",
        munzee_id: 1846,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Saint Patrick's Day 2019",
    id: "saintpatrick's day 20192019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Pot o' Gold",
        icons: ["poto'gold"],
        id: "poto'gold",
        munzee_id: 1825,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "WallaWee Fella",
        icons: ["wallaweefella"],
        id: "wallaweefella",
        munzee_id: 1826,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Valentine's Day 2019",
    id: "valentines day 20192019",
    starts: "2019-00-00T00:00:00-05:00",
    ends: "2019-00-00T00:00:00-05:00",
    specials: [
      {
        name: "Heavenly Hammock",
        icons: ["heavenlyhammock"],
        id: "heavenlyhammock",
        munzee_id: 1762,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Green Throwback Candy Heart",
        icons: ["greenthrowbackcandyheart"],
        id: "greenthrowbackcandyheart",
        munzee_id: 1764,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Yellow Throwback Candy Heart",
        icons: ["yellowthrowbackcandyheart"],
        id: "yellowthrowbackcandyheart",
        munzee_id: 1763,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Orange Throwback Candy Heart",
        icons: ["orangethrowbackcandyheart"],
        id: "orangethrowbackcandyheart",
        munzee_id: 1765,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Red Throwback Candy Heart",
        icons: ["redthrowbackcandyheart"],
        id: "redthrowbackcandyheart",
        munzee_id: 1766,
        duration: 12,
        lands_on: ["munzee"],
      },
    ],
  },
];

export default s2019;