import { SeasonalCategory } from ".";
import { TypeHidden, TypeState, TypeTags } from "@cuppazee/db";

const s2020: SeasonalCategory[] = [
  {
    name: "20/20 Vision",
    id: "vision2020",
    starts: "2020-01-02T15:00:00-06:00",
    ends: "2020-12-31T23:59:00-06:00",
    specials: [
      {
        name: "Spectacular Spectacles",
        icons: ["spectacularspectacles2020vision"],
        id: "spectacularspectacles2020vision",
        munzee_id: 2282,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "The King's Sunglasses",
        icons: ["theking'ssunglasses2020vision"],
        id: "theking'ssunglasses2020vision",
        munzee_id: 2283,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Welding Goggles",
        icons: ["weldinggoggles2020vision"],
        id: "weldinggoggles2020vision",
        munzee_id: 2284,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Flip Glasses",
        icons: ["flipglasses2020vision"],
        id: "flipglasses2020vision",
        munzee_id: 2285,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Ski Goggles",
        icons: ["skigoggles2020vision"],
        id: "skigoggles2020vision",
        munzee_id: 2286, //
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Theatre Binoculars",
        icons: ["theatrebinoculars2020vision"],
        id: "theatrebinoculars2020vision",
        munzee_id: 2287,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Joke Glasses",
        icons: ["jokeglasses2020vision"],
        id: "jokeglasses2020vision",
        munzee_id: 2288, //
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "3D Glasses",
        icons: ["3dglasses2020vision"],
        id: "3dglasses2020vision",
        munzee_id: 2289,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Viewfinder",
        icons: ["viewfinder2020vision"],
        id: "viewfinder2020vision",
        munzee_id: 2290,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "VR Goggles",
        icons: ["vrgoggles2020vision"],
        id: "vrgoggles2020vision",
        munzee_id: 2291,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Jeweler Loupe",
        icons: ["jewelerloupe2020vision", "jewelerloupe2020glasses"],
        id: "jewelerloupe2020vision",
        munzee_id: 2292,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Aviator",
        icons: ["aviator2020vision", "aviators2020vision"],
        id: "aviator2020vision",
        munzee_id: 2293,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Summer Shades",
        icons: ["summershades2020vision"],
        id: "summershades2020vision",
        munzee_id: 2294,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Party Glasses",
        icons: ["partyglasses2020vision"],
        id: "partyglasses2020vision",
        munzee_id: 2295,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Broken Glasses",
        icons: ["brokenglasses2020vision"],
        id: "brokenglasses2020vision",
        munzee_id: 2296,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Emerald City Glasses",
        icons: ["emeraldcityglasses2020vision"],
        id: "emeraldcityglasses2020vision",
        munzee_id: 2297,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Peace Glasses",
        icons: ["peaceglasses2020vision"],
        id: "peaceglasses2020vision",
        munzee_id: 2298,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Hunting Glasses",
        icons: ["huntingglasses2020vision"],
        id: "huntingglasses2020vision",
        munzee_id: 2299,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Cat-Eye Glasses",
        icons: ["cat-eyeglasses2020vision"],
        id: "cat-eyeglasses2020vision",
        munzee_id: 2300,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Disguise Glasses",
        icons: ["disguiseglasses2020vision"],
        id: "disguiseglasses2020vision",
        munzee_id: 2301,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Microscope Glasses",
        icons: ["microscopeglasses2020vision"],
        id: "microscopeglasses2020vision",
        munzee_id: 2302,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Meme Glasses",
        icons: ["memeglasses2020vision"],
        id: "memeglasses2020vision",
        munzee_id: 2303,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Glow in the Dark Glasses",
        icons: ["glowinthedarkglasses2020vision"],
        id: "glowinthedarkglasses2020vision",
        munzee_id: 2304,
        duration: 12,
        lands_on: ["munzee"],
      },
      {
        name: "Eclipse Glasses",
        icons: ["eclipseglasses2020vision"],
        id: "eclipseglasses2020vision",
        munzee_id: 2305,
        duration: 12,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
    ],
  },
  {
    name: "Fr057y",
    id: "christmas2020",
    starts: "2020-12-01T00:00:00-05:00",
    ends: "2020-12-31T23:59:00-05:00",
    pobs: [
      {
        name: "Fr057y",
        icons: ["fr057y"],
        id: "fr057y",
        munzee_id: 2743,
        lands_on: [],
      },
    ],
  },
  {
    name: "Christmas 2020",
    id: "christmas2020",
    starts: "2020-12-01T00:00:00-05:00",
    ends: "2020-12-31T23:59:00-05:00",
    pobs: [
      {
        name: "Cyborg Santa",
        icons: ["cyborgsanta"],
        id: "cyborgsanta",
        munzee_id: 2695,
        lands_on: [],
      },
      {
        name: "Cybersaurus Rex",
        icons: ["cybersaurusrex"],
        id: "cybersaurusrex",
        munzee_id: 2696,
        lands_on: [],
      },
      {
        name: "GingerMech Man",
        icons: ["gingermechman"],
        id: "gingermechman",
        munzee_id: 2703,
        lands_on: [],
      },
      {
        name: "GingerSnapped Man",
        icons: ["gingersnappedman"],
        id: "gingersnappedman",
        munzee_id: 2730,
        lands_on: [],
      },
      {
        name: "ReinDroid",
        icons: ["reindroid"],
        id: "reindroid",
        munzee_id: 2735,
        lands_on: [],
      },
      {
        name: "Fleeting ReinDroid",
        icons: ["fleetingreindroid"],
        id: "fleetingreindroid",
        munzee_id: 2736,
        lands_on: [],
      },
      {
        name: "RUD01PH",
        icons: ["rud01ph"],
        id: "rud01ph",
        munzee_id: 2737,
        lands_on: [],
      },
      {
        name: "Fleeting RUD01PH",
        icons: ["fleetingrud01ph"],
        id: "fleetingrud01ph",
        munzee_id: 2738,
        lands_on: [],
      },
      {
        name: "31F",
        icons: ["31f"],
        id: "31f",
        munzee_id: 2739,
        lands_on: [],
      },
      {
        name: "KrampBot",
        icons: ["krampbot"],
        id: "krampbot",
        munzee_id: 2740,
        lands_on: [],
      },
    ],
    types: [
      {
        name: "Pixel Present",
        icons: ["pixelpresent"],
        id: "pixelpresent",
        munzee_id: 2704,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Snowball",
        icons: ["snowball"],
        id: "snowball",
        munzee_id: 2697,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Rainbow Snowcone",
        icons: ["rainbowsnowcone"],
        id: "rainbowsnowcone",
        munzee_id: 2699,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "ChristmaZ Tree",
        icons: ["christmaztree"],
        id: "christmaztree",
        munzee_id: 2700,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "ChristmaZ Pickle",
        icons: ["christmazpickle"],
        id: "christmazpickle",
        munzee_id: 2702,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
    ],
  },
  {
    name: "Walla EggZ",
    id: "wallaeggz2020",
    starts: "2020-11-24T12:00:00-05:00",
    ends: "2020-12-15T23:59:00-05:00",
    specials: [
      {
        name: "Walla Joy Egg",
        icons: ["wallajoyegg"],
        id: "wallajoyegg",
        duration: 4,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          type => type.has_tag(TypeTags.TypeGaming) && type.state === TypeState.Virtual,
        ],
        hidden: [TypeHidden.Capture],
      },
      {
        name: "Walla Surprise Egg",
        icons: ["wallasurpriseegg"],
        id: "wallasurpriseegg",
        duration: 4,
        lands_on: [
          "munzee",
          "egg",
          type => type.has_tag(TypeTags.TypeGaming) && type.state === TypeState.Physical,
        ],
        hidden: [TypeHidden.Capture],
      },
      {
        name: "Chocolate Honeycombs",
        icons: ["chocolatehoneycombs"],
        id: "chocolatehoneycombs",
        munzee_id: 2714,
        duration: 4,
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Green Unicorn Toy Rocker",
        icons: ["greenunicorntoyrocker"],
        id: "greenunicorntoyrocker",
        munzee_id: 2710,
        duration: 4,
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Mixed Candy",
        icons: ["mixedcandy"],
        id: "mixedcandy",
        munzee_id: 2709,
        duration: 4,
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Mini Bubbles",
        icons: ["minibubbles"],
        id: "minibubbles",
        munzee_id: 2712,
        duration: 4,
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Popper Toy",
        icons: ["poppertoy"],
        id: "poppertoy",
        munzee_id: 2707,
        duration: 4,
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Gummy WallaBees",
        icons: ["gummywallabees"],
        id: "gummywallabees",
        munzee_id: 2713,
        duration: 4,
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Plastic Dinosaur",
        icons: ["plasticdinosaur"],
        id: "plasticdinosaur",
        munzee_id: 2708,
        duration: 4,
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Pink Unicorn Toy Rocker",
        icons: ["pinkunicorntoyrocker"],
        id: "pinkunicorntoyrocker",
        munzee_id: 2715,
        duration: 4,
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
    ],
  },
  {
    name: "Christmas Critters",
    id: "christmascritter2020",
    starts: "2020-11-01T00:00:00-05:00",
    ends: "2020-12-31T23:59:00-05:00",
    pobs: [
      {
        name: "Baby Hippo",
        icons: ["babyhippo"],
        id: "babyhippo",
        munzee_id: 2648,
        lands_on: ["treehouse", "munzee", "watermystery"],
      },
      {
        name: "Baby Alpaca",
        icons: ["babyalpaca"],
        id: "babyalpaca",
        munzee_id: 2649,
        lands_on: ["skyland", ":virtual", "electricmystery"],
      },
      {
        name: "Baby Reindeer",
        icons: ["babyreindeer"],
        id: "babyreindeer",
        munzee_id: 2647,
        lands_on: ["treehouse", "munzee", "icemystery", "skyland", ":virtual"],
      },
    ],
  },
  {
    name: "Deathly DeeZert",
    id: "halloween2020",
    starts: "2020-10-27T12:00:00-05:00",
    ends: "2020-11-15T23:59:00-05:00",
    specials: [
      {
        name: "Creepy Cauldron",
        icons: ["creepycauldron"],
        id: "creepycauldron",
        munzee_id: 2630,
        duration: 4,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "airmystery",
          "electricmystery",
          "flatrob",
          "flatmatt",
          "flatlou",
          "flathammock",
        ],
      },
      {
        name: "Pumpkin Pail",
        icons: ["pumpkinpail"],
        id: "pumpkinpail",
        munzee_id: 2635,
        duration: 4,
        lands_on: [
          "munzee",
          "mystery",
          "firemystery",
          "earthmystery",
          "watermystery",
          "icemystery",
        ],
      },
      {
        name: "Mummy Macaron",
        icons: ["mummymacaron"],
        id: "mummymacaron",
        munzee_id: 2631,
        duration: 4,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "airmystery",
          "electricmystery",
          "flatrob",
          "flatmatt",
          "flatlou",
          "flathammock",
        ],
      },
      {
        name: "Pumpkin Pop",
        icons: ["pumpkinpop"],
        id: "pumpkinpop",
        munzee_id: 2632,
        duration: 4,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "airmystery",
          "electricmystery",
          "flatrob",
          "flatmatt",
          "flatlou",
          "flathammock",
        ],
      },
      {
        name: "Blood Sucker",
        icons: ["bloodsucker"],
        id: "bloodsucker",
        munzee_id: 2633,
        duration: 4,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "airmystery",
          "electricmystery",
          "flatrob",
          "flatmatt",
          "flatlou",
          "flathammock",
        ],
      },
      {
        name: "Rock",
        icons: ["rock"],
        id: "rock",
        munzee_id: 2634,
        duration: 4,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "airmystery",
          "electricmystery",
          "flatrob",
          "flatmatt",
          "flatlou",
          "flathammock",
        ],
      },
      {
        name: "Bonbon Bat",
        icons: ["bonbonbat"],
        id: "bonbonbat",
        duration: 4,
        lands_on: [
          "munzee",
          "mystery",
          "firemystery",
          "earthmystery",
          "watermystery",
          "icemystery",
        ],
      },
      {
        name: "Frappenstein",
        icons: ["frappenstein"],
        id: "frappenstein",
        munzee_id: 2637,
        duration: 4,
        lands_on: [
          "munzee",
          "mystery",
          "firemystery",
          "earthmystery",
          "watermystery",
          "icemystery",
        ],
      },
      {
        name: "Boo Brownie",
        icons: ["boobrownie"],
        id: "boobrownie",
        munzee_id: 2638,
        duration: 4,
        lands_on: [
          "munzee",
          "mystery",
          "firemystery",
          "earthmystery",
          "watermystery",
          "icemystery",
        ],
      },
      {
        name: "Toothbrush",
        icons: ["toothbrush"],
        id: "toothbrush",
        munzee_id: 2639,
        duration: 4,
        lands_on: [
          "munzee",
          "mystery",
          "firemystery",
          "earthmystery",
          "watermystery",
          "icemystery",
        ],
      },
    ],
  },
  {
    name: "Zeecret Agents",
    id: "zeecret2020",
    starts: "2020-10-08T12:00:00-05:00",
    ends: "2020-11-08T23:59:00-05:00",
    specials: [
      {
        name: "PINE Agent",
        icons: ["pineagent"],
        id: "pineagent",
        munzee_id: 2616,
        duration: 4,
        lands_on: [
          "munzee",
          "mystery",
          "earthmystery",
          type => type.has_tag(TypeTags.TypeVirtual),
          "selfdestructcard",
          "briefcase",
          "nightvisiongoggles",
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "PEAR Agent",
        icons: ["pearagent"],
        id: "pearagent",
        munzee_id: 2615,
        duration: 4,
        lands_on: [
          "munzee",
          "mystery",
          "earthmystery",
          type => type.has_tag(TypeTags.TypeVirtual),
          "selfdestructcard",
          "briefcase",
          "nightvisiongoggles",
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "Virtual Pineamite",
        icons: ["virtualpineamite"],
        id: "virtualpineamite",
        munzee_id: 2614,
        duration: 4,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "selfdestructcard",
          "nightvisiongoggles",
        ],
      },
      {
        name: "Physical Pineamite",
        icons: ["physicalpineamite"],
        id: "physicalpineamite",
        munzee_id: 2613,
        duration: 4,
        lands_on: ["munzee", "mystery", "earthmystery", "briefcase"],
      },
      {
        name: "Virtual Pear Bomb",
        icons: ["virtualpearbomb"],
        id: "virtualpearbomb",
        munzee_id: 2612,
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "selfdestructcard",
          "nightvisiongoggles",
        ],
      },
      {
        name: "Physical Pear Bomb",
        icons: ["physicalpearbomb"],
        id: "physicalpearbomb",
        munzee_id: 2611,
        duration: 4,
        lands_on: ["munzee", "mystery", "earthmystery", "briefcase"],
      },
    ],
  },
  {
    name: "Bash from the Past",
    id: "bash2020",
    starts: "2020-09-21T14:30:00-05:00",
    ends: "2020-10-11T23:59:00-05:00",
    specials: [
      {
        name: "Beer Boot",
        icons: ["oktoberfestbash-beerboot"],
        id: "oktoberfestbash-beerboot",
        munzee_id: 2594,
        duration: 6,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "airmystery", "electricmystery"],
      },
      {
        name: "Paint Pallette",
        icons: ["artwalkbash-paintpalette"],
        id: "artwalkbash-paintpalette",
        munzee_id: 2595,
        duration: 6,
        lands_on: [
          "munzee",
          "firemystery",
          "mystery",
          "icemystery",
          "watermystery",
          "earthmystery",
        ],
      },
      {
        name: "Yellow Rose",
        icons: ["lonestarbash-yellowrose"],
        id: "lonestarbash-yellowrose",
        munzee_id: 2596,
        duration: 6,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "airmystery", "electricmystery"],
      },
      {
        name: "Playing Cards",
        icons: ["all-inbash-playingcards"],
        id: "all-inbash-playingcards",
        munzee_id: 2597,
        duration: 6,
        lands_on: [
          "munzee",
          "firemystery",
          "mystery",
          "icemystery",
          "watermystery",
          "earthmystery",
        ],
      },
      {
        name: "Ghost",
        icons: ["mh-boobash-ghost"],
        id: "mh-boobash-ghost",
        munzee_id: 2598,
        duration: 6,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "airmystery", "electricmystery"],
      },
      {
        name: "Unicorn Stick Horse",
        icons: ["medzeevaltimesbash-unicornstickhorse"],
        id: "medzeevaltimesbash-unicornstickhorse",
        munzee_id: 2599,
        duration: 6,
        lands_on: [
          "munzee",
          "firemystery",
          "mystery",
          "icemystery",
          "watermystery",
          "earthmystery",
        ],
      },
      {
        name: "ZeeOps Transmission",
        icons: ["bashfromthepast-zeeopstransmission"],
        id: "bashfromthepast-zeeopstransmission",
        munzee_id: 2600,
        duration: 6,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "airmystery", "electricmystery"],
      },
    ],
  },
  {
    name: "National Waffle Day",
    id: "waffleday2020",
    starts: "2020-08-24T12:00:00-05:00",
    ends: "2020-09-14T23:59:00-05:00",
    specials: [
      {
        name: "Belgian Waffle",
        icons: ["belgianwaffle"],
        id: "belgianwaffle",
        munzee_id: 2583,
        duration: 4,
        lands_on: ["munzee", "calf", "cow", "milk", "piglet", "pig", "bacon"],
      },
      {
        name: "Stroopwafel",
        icons: ["stroopwafel"],
        id: "stroopwafel",
        munzee_id: 2584,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "chick", "chicken", "egg"],
      },
    ],
  },
  {
    name: "Camp Critters",
    id: "campcritter2020",
    starts: "2020-08-01T00:00:00-05:00",
    ends: "2020-09-31T23:59:00-05:00",
    pobs: [
      {
        name: "Baby Fox",
        icons: ["babyfox", "undefined"],
        id: "babyfox",
        munzee_id: 2561,
        lands_on: ["skyland", ":virtual", "airmystery", "poicampground"],
      },
      {
        name: "Baby Moose",
        icons: ["babymoose"],
        id: "babymoose",
        munzee_id: 2560,
        lands_on: ["treehouse", "munzee", "earthmystery", "watermystery"],
      },
      {
        name: "Baby Squirrel",
        icons: ["babysquirrel"],
        id: "babysquirrel",
        munzee_id: 2559,
        lands_on: [
          "treehouse",
          "munzee",
          "earthmystery",
          "watermystery",
          "skyland",
          ":virtual",
          "airmystery",
          "poicampground",
        ],
      },
      {
        name: "Bear Cub",
        icons: ["bearcub"],
        id: "bearcub",
        munzee_id: 2558,
        lands_on: [
          "treehouse",
          "munzee",
          "earthmystery",
          "watermystery",
          "skyland",
          ":virtual",
          "airmystery",
          "poicampground",
        ],
      },
    ],
  },
  {
    name: "Camp Counselors",
    id: "campcounselors2020",
    starts: "2020-07-29T12:00:00-05:00",
    ends: "2020-09-09T23:59:00-05:00",
    specials: [
      {
        name: "Counselor Cap-A-Lot",
        icons: ["campcap-a-lotcounselor"],
        id: "campcap-a-lotcounselor",
        munzee_id: 2565,
        duration: 6,
        lands_on: [
          "treehouse",
          "skyland",
          type => type.has_tag(TypeTags.TypeMystery),
          "munzee",
          type => type.has_tag(TypeTags.TypeVirtual),
        ],
      },
      {
        name: "Counselor QRantine",
        icons: ["campqrantinecounselor"],
        id: "campqrantinecounselor",
        munzee_id: 2566,
        duration: 6,
        lands_on: [
          "treehouse",
          "skyland",
          type => type.has_tag(TypeTags.TypeMystery),
          "munzee",
          type => type.has_tag(TypeTags.TypeVirtual),
        ],
      },
      {
        name: "Counselor FrEEZ",
        icons: ["campfreezcounselor"],
        id: "campfreezcounselor",
        munzee_id: 2567,
        duration: 6,
        lands_on: [
          "treehouse",
          "skyland",
          type => type.has_tag(TypeTags.TypeMystery),
          "munzee",
          type => type.has_tag(TypeTags.TypeVirtual),
        ],
      },
      {
        name: "Counselor KenneZee",
        icons: ["campkennezeecounselor"],
        id: "campkennezeecounselor",
        munzee_id: 2568,
        duration: 6,
        lands_on: [
          "treehouse",
          "skyland",
          type => type.has_tag(TypeTags.TypeMystery),
          "munzee",
          type => type.has_tag(TypeTags.TypeVirtual),
        ],
      },
    ],
  },
  {
    name: "Munzee's 9th Birthday",
    id: "munzeebirthday2020",
    starts: "2020-07-09T12:00:00-05:00",
    ends: "2020-08-09T23:59:00-05:00",
    specials: [
      {
        name: "Red Water Balloon",
        icons: ["redwaterballoon"],
        id: "redwaterballoon",
        munzee_id: 2545,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Green Water Balloon",
        icons: ["greenwaterballoon"],
        id: "greenwaterballoon",
        munzee_id: 2546,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Blue Water Balloon",
        icons: ["bluewaterballoon"],
        id: "bluewaterballoon",
        munzee_id: 2547,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Yellow Water Balloon",
        icons: ["yellowwaterballoon"],
        id: "yellowwaterballoon",
        munzee_id: 2548,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Camp Cap-A-Lot Flag",
        icons: ["campcap-a-lotflag"],
        id: "campcap-a-lotflag",
        munzee_id: 2549,
        duration: 2,
        lands_on: [
          "munzee",
          "earthmystery",
          "treehouse",
          "skyland",
          type => type.has_tag(TypeTags.TypeVirtual),
        ],
      },
      {
        name: "Camp QRantine Flag",
        icons: ["campqrantineflag"],
        id: "campqrantineflag",
        munzee_id: 2550,
        duration: 2,
        lands_on: [
          "munzee",
          "earthmystery",
          "treehouse",
          "skyland",
          type => type.has_tag(TypeTags.TypeVirtual),
        ],
      },
      {
        name: "Camp FrEEZ Flag",
        icons: ["campfreezflag"],
        id: "campfreezflag",
        munzee_id: 2551,
        duration: 2,
        lands_on: [
          "munzee",
          "earthmystery",
          "treehouse",
          "skyland",
          type => type.has_tag(TypeTags.TypeVirtual),
        ],
      },
      {
        name: "Camp KenneZee Flag",
        icons: ["campkennezeeflag"],
        id: "campkennezeeflag",
        munzee_id: 2552,
        duration: 2,
        lands_on: [
          "munzee",
          "earthmystery",
          "treehouse",
          "skyland",
          type => type.has_tag(TypeTags.TypeVirtual),
        ],
      },
    ],
  },
  {
    name: "World Sushi Day Ingredients",
    id: "worldsushiday2020",
    starts: "2020-06-18T12:00:00-05:00",
    ends: "2020-07-08T23:59:00-05:00",
    specials: [
      {
        name: "Cucumber",
        icons: ["cucumber"],
        id: "cucumber",
        munzee_id: 2512,
        duration: 3,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          "farmer",
          "farmerandwife",
          "family",
        ],
      },
      {
        name: "Fried Egg",
        icons: ["friedegg"],
        id: "friedegg",
        munzee_id: 2513,
        duration: 4,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          "farmer",
          "farmerandwife",
          "family",
        ],
      },
      {
        name: "Puffer Fish",
        icons: ["pufferfish"],
        id: "pufferfish",
        munzee_id: 2516,
        duration: 9,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          "farmer",
          "farmerandwife",
          "family",
        ],
      },
      {
        name: "Rice",
        icons: ["rice"],
        id: "rice",
        munzee_id: 2517,
        duration: 1,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          "farmer",
          "farmerandwife",
          "family",
        ],
      },
      {
        name: "Roe",
        icons: ["roe"],
        id: "roe",
        munzee_id: 2518,
        duration: 7,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          "farmer",
          "farmerandwife",
          "family",
        ],
      },
      {
        name: "Salmon",
        icons: ["salmon"],
        id: "salmon",
        munzee_id: 2519,
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          "farmer",
          "farmerandwife",
          "family",
        ],
      },
      {
        name: "Nori",
        icons: ["nori"],
        id: "nori",
        munzee_id: 2514,
        duration: 2,
        lands_on: ["watermystery", "mystery", "aquamarine", "longsword", "battleaxe"],
      },
      {
        name: "Prawn",
        icons: ["prawn"],
        id: "prawn",
        munzee_id: 2515,
        duration: 5,
        lands_on: ["watermystery", "mystery", "aquamarine", "longsword", "battleaxe"],
      },
      {
        name: "Tuna",
        icons: ["tuna"],
        id: "tuna",
        munzee_id: 2520,
        duration: 8,
        lands_on: ["watermystery", "mystery", "aquamarine", "longsword", "battleaxe"],
      },
    ],
  },
  {
    name: "World Sushi Day Masters",
    id: "worldsushidaymasters2020",
    starts: "2020-06-18T12:00:00-05:00",
    ends: "2020-07-08T23:59:00-05:00",
    specials: [
      {
        name: "Neko",
        icons: ["sushimasterneko"],
        id: "sushimasterneko",
        munzee_id: 2521,
        duration: 6,
        lands_on: [
          "watermystery",
          "mystery",
          "aquamarine",
          "longsword",
          "battleaxe",
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          "farmer",
          "farmerandwife",
          "family",
        ],
      },
      {
        name: "Kappa",
        icons: ["sushimasterkappa"],
        id: "sushimasterkappa",
        munzee_id: 2522,
        duration: 6,
        lands_on: [
          "watermystery",
          "mystery",
          "aquamarine",
          "longsword",
          "battleaxe",
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          "farmer",
          "farmerandwife",
          "family",
        ],
      },
      {
        name: "Yurei",
        icons: ["sushimasteryurei"],
        id: "sushimasteryurei",
        munzee_id: 2523,
        duration: 6,
        lands_on: [
          "watermystery",
          "mystery",
          "aquamarine",
          "longsword",
          "battleaxe",
          type => type.has_tag(TypeTags.TypeVirtual),
          "eggs",
          "farmer",
          "farmerandwife",
          "family",
        ],
      },
    ],
  },
  {
    name: "Aquatic Baby Animals",
    id: "aquaticbabyanimals2020",
    starts: "2020-06-05T12:00:00-05:00",
    ends: "2020-06-21T23:59:00-05:00",
    specials: [
      {
        name: "Baby Narwhal",
        icons: ["babynarwhal"],
        id: "babynarwhal",
        munzee_id: 2508,
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.VirtualColourBlue),
          "seaweed",
          "fish",
          "shark",
          "canoe",
          "motorboat",
          "submarine",
          "planulalarva",
          "polyp",
        ],
      },
      {
        name: "Baby Penguin",
        icons: ["babypenguin"],
        id: "babypenguin",
        munzee_id: 2509,
        duration: 5,
        lands_on: [
          type => type.has_tag(TypeTags.VirtualColourBlue),
          "seaweed",
          "fish",
          "shark",
          "canoe",
          "motorboat",
          "submarine",
          "planulalarva",
          "polyp",
        ],
      },
      {
        name: "Baby Crab",
        icons: ["babycrab"],
        id: "babycrab",
        munzee_id: 2507,
        duration: 4,
        lands_on: [
          "watermystery",
          "mystery",
          "aquamarine",
          "turtleegg",
          "turtlehatchling",
          "juvenileturtle",
        ],
      },
      {
        name: "Seal Pup",
        icons: ["sealpup"],
        id: "sealpup",
        munzee_id: 2510,
        duration: 3,
        lands_on: [
          type => type.has_tag(TypeTags.VirtualColourBlue),
          "seaweed",
          "fish",
          "shark",
          "canoe",
          "motorboat",
          "submarine",
          "planulalarva",
          "polyp",
        ],
      },
      {
        name: "Baby Shark",
        icons: ["babyshark"],
        id: "babyshark",
        munzee_id: 2511,
        duration: 2,
        lands_on: [
          type => type.has_tag(TypeTags.VirtualColourBlue),
          "seaweed",
          "fish",
          "shark",
          "canoe",
          "motorboat",
          "submarine",
          "planulalarva",
          "polyp",
        ],
      },
    ],
  },
  {
    name: "Hometown Heroes 2020",
    id: "hometownheroes2020",
    starts: "2020-05-18T12:00:00-05:00",
    ends: "2020-06-07T23:59:00-05:00",
    specials: [
      {
        name: "Stay Safe",
        icons: ["staysafe"],
        id: "staysafe",
        munzee_id: 2482,
        duration: 2,
        lands_on: ["virtual"],
      },
      {
        name: "Grocery Hero",
        icons: ["groceryhero"],
        id: "groceryhero",
        munzee_id: 2485,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "First Responder Hero",
        icons: ["firstresponderhero"],
        id: "firstresponderhero",
        munzee_id: 2487,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Healthcare Hero",
        icons: ["healthcarehero"],
        id: "healthcarehero",
        munzee_id: 2486,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Education Hero",
        icons: ["educationhero"],
        id: "educationhero",
        munzee_id: 2484,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Delivery Hero",
        icons: ["deliveryhero"],
        id: "deliveryhero",
        munzee_id: 2483,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Grocery Hero Mask",
        icons: ["groceryheromask"],
        id: "groceryheromask",
        munzee_id: 2490,
        duration: 6,
        lands_on: [
          "virtual_amethyst",
          "virtual_sapphire",
          "airmystery",
          "virtual_citrine",
          "virtual_onyx",
          "electricmystery",
          "skyland",
        ],
      },
      {
        name: "First Responder Hero Mask",
        icons: ["firstresponderheromask"],
        id: "firstresponderheromask",
        munzee_id: 2492,
        duration: 6,
        lands_on: [
          "virtual_amethyst",
          "virtual_sapphire",
          "airmystery",
          "virtual_citrine",
          "virtual_onyx",
          "electricmystery",
          "skyland",
        ],
      },
      {
        name: "Health Hero Mask",
        icons: ["healthheromask"],
        id: "healthheromask",
        munzee_id: 2491,
        duration: 6,
        lands_on: [
          "virtual_amethyst",
          "virtual_sapphire",
          "airmystery",
          "virtual_citrine",
          "virtual_onyx",
          "electricmystery",
          "skyland",
        ],
      },
      {
        name: "Education Hero Mask",
        icons: ["educationheromask"],
        id: "educationheromask",
        munzee_id: 2489,
        duration: 6,
        lands_on: [
          "virtual_amethyst",
          "virtual_sapphire",
          "airmystery",
          "virtual_citrine",
          "virtual_onyx",
          "electricmystery",
          "skyland",
        ],
      },
      {
        name: "Delivery Hero Mask",
        icons: ["deliveryheromask"],
        id: "deliveryheromask",
        munzee_id: 2488,
        duration: 6,
        lands_on: [
          "virtual_amethyst",
          "virtual_sapphire",
          "airmystery",
          "virtual_citrine",
          "virtual_onyx",
          "electricmystery",
          "skyland",
        ],
      },
    ],
  },
  {
    name: "Baby Animals",
    id: "babyanimals2020",
    starts: "2020-05-01T00:00:00-05:00",
    ends: "2020-06-30T23:59:00-05:00",
    pobs: [
      {
        name: "Hedgehog",
        icons: ["hedgehog"],
        id: "hedgehog",
        munzee_id: 2427,
        lands_on: [
          "skyland",
          "treehouse",
          "earthmystery",
          "icemystery",
          "flatlou",
          type =>
            type.has_tag(TypeTags.TypeVirtual) &&
            ![
              "virtual",
              "virtual_black",
              "virtual_timberwolf",
              "virtual_gray",
              "virtual_silver",
            ].includes(type.icon),
        ],
      },
      {
        name: "Polar Bear",
        icons: ["polarbear"],
        id: "polarbear",
        munzee_id: 2428,
        lands_on: [
          "skyland",
          "treehouse",
          "earthmystery",
          "icemystery",
          "flatlou",
          type =>
            type.has_tag(TypeTags.TypeVirtual) &&
            ![
              "virtual",
              "virtual_black",
              "virtual_timberwolf",
              "virtual_gray",
              "virtual_silver",
            ].includes(type.icon),
        ],
      },
      {
        name: "Owlet",
        icons: ["owlet"],
        id: "owlet",
        munzee_id: 2429,
        lands_on: [
          "skyland",
          "treehouse",
          "virtual",
          "airmystery",
          "electricmystery",
          "flathammock",
        ],
      },
    ],
  },
  {
    name: "World Laughter Day 2020",
    id: "worldlaughterday2020",
    starts: "2020-05-01T10:00:00-05:00",
    ends: "2020-05-17T23:59:00-05:00",
    specials: [
      {
        name: "Bison Joke",
        icons: ["bisonjoke"],
        id: "bisonjoke",
        munzee_id: 2437,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Chilly Joke",
        icons: ["chillyjoke"],
        id: "chillyjoke",
        munzee_id: 2441,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Librarian Joke",
        icons: ["librarianjoke"],
        id: "librarianjoke",
        munzee_id: 2436,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Cyclist Joke",
        icons: ["cyclistjoke"],
        id: "cyclistjoke",
        munzee_id: 2442,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Pirate Joke",
        icons: ["piratejoke"],
        id: "piratejoke",
        munzee_id: 2435,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Dad Joke",
        icons: ["dadjoke"],
        id: "dadjoke",
        munzee_id: 2439,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Unicorn Joke",
        icons: ["unicornjoke"],
        id: "unicornjoke",
        munzee_id: 2444,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Grape Joke",
        icons: ["grapejoke"],
        id: "grapejoke",
        munzee_id: 2440,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Ninja Joke",
        icons: ["ninjajoke"],
        id: "ninjajoke",
        munzee_id: 2443,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "Fishy Joke",
        icons: ["fishyjoke"],
        id: "fishyjoke",
        munzee_id: 2438,
        duration: 5.05,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
    ],
  },
  {
    name: "Petting Zoo 2020",
    id: "pettingzoo2020",
    starts: "2020-04-09T11:11:00-05:00",
    ends: "2020-04-30T23:59:00-05:00",
    specials: [
      {
        name: "Baby Fawn",
        icons: ["babyfawn"],
        id: "babyfawn",
        munzee_id: 2417,
        duration: 1,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "electricmystery",
          "surprise",
          "virtual_onyx",
          "virtual_citrine",
        ],
      },
      {
        name: "Baby Tiger",
        icons: ["babytiger"],
        id: "babytiger",
        munzee_id: 2419,
        duration: 1,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "electricmystery",
          "surprise",
          "virtual_onyx",
          "virtual_citrine",
        ],
      },
      {
        name: "Baby Lamb",
        icons: ["babylamb"],
        id: "babylamb",
        munzee_id: 2418,
        duration: 1,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "electricmystery",
          "surprise",
          "virtual_onyx",
          "virtual_citrine",
        ],
      },
      {
        name: "Baby Chick",
        icons: ["babychick"],
        id: "babychick",
        munzee_id: 2416,
        duration: 1,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "electricmystery",
          "surprise",
          "virtual_onyx",
          "virtual_citrine",
        ],
      },
      {
        name: "Baby Bunny",
        icons: ["babybunny"],
        id: "babybunny",
        munzee_id: 2415,
        duration: 1,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "electricmystery",
          "surprise",
          "virtual_onyx",
          "virtual_citrine",
        ],
      },
    ],
  },
  {
    name: "Lou Roll 2020",
    id: "louroll2020",
    starts: "2020-03-31T11:11:00-05:00",
    ends: "2020-04-13T23:11:00-05:00",
    specials: [
      {
        name: "Lou Roll",
        icons: ["louroll"],
        id: "louroll",
        munzee_id: 2411,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "flatlou"],
      },
    ],
  },
  {
    name: "Rainbow Trail 2020",
    id: "rainbowtrail2020",
    starts: "2020-03-17T13:00:00-05:00",
    ends: "2020-03-31T23:59:00-05:00",
    specials: [
      {
        name: "Rainbow Trail",
        icons: ["rainbowtrail"],
        id: "rainbowtrail",
        munzee_id: 2394,
        duration: 7,
        lands_on: ["munzee", "shamrock", "earthmystery"],
        meta: {
          scatterer_radius: 1000,
          scatterer_types: [2395, 2396, 2397, 2398, 2399, 2400, 2401],
          scatterer_min: 1,
          scatterer_max: 3,
        },
      },
    ],
    types: [
      {
        name: "Red ZED",
        icons: ["redzed"],
        id: "redzed",
        munzee_id: 2395,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 1,
        },
      },
      {
        name: "Orange ZED",
        icons: ["orangezed"],
        id: "orangezed",
        munzee_id: 2396,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 1,
        },
      },
      {
        name: "Yellow ZED",
        icons: ["yellowzed"],
        id: "yellowzed",
        munzee_id: 2397,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 1,
        },
      },
      {
        name: "Green ZED",
        icons: ["greenzed"],
        id: "greenzed",
        munzee_id: 2398,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 1,
        },
      },
      {
        name: "Blue ZED",
        icons: ["bluezed"],
        id: "bluezed",
        munzee_id: 2399,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 1,
        },
      },
      {
        name: "Indigo ZED",
        icons: ["indigozed"],
        id: "indigozed",
        munzee_id: 2400,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 1,
        },
      },
      {
        name: "Violet ZED",
        icons: ["violetzed"],
        id: "violetzed",
        munzee_id: 2401,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 1,
        },
      },
    ],
  },
  {
    name: "Flat Day the 13th pt.3 2020",
    id: "flatdaythe13thpt.32020",
    starts: "2020-03-12T13:00:00-05:00",
    ends: "2020-03-17T13:00:00-05:00",
    specials: [
      {
        name: "THE RETURN",
        icons: ["thereturn"],
        id: "thereturn",
        munzee_id: 2393,
        duration: 6,
        lands_on: ["munzee"],
      },
    ],
  },
  {
    name: "Leap Day 2020",
    id: "leapday2020",
    starts: "2020-02-28T12:00:00-06:00",
    ends: "2020-03-03T10:00:00-06:00",
    specials: [
      {
        name: "H.Zee. Wells’ Time Machine",
        icons: ["h.zee.wells'timemachine"],
        id: "h.zee.wells'timemachine",
        munzee_id: 2363,
        duration: 4,
        lands_on: ["munzee", "premium", "mace", "mystery"],
      },
      {
        name: "Zeeloreon Time Traveler",
        icons: ["zeeloreontimetraveler"],
        id: "zeeloreontimetraveler",
        munzee_id: 2364,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
      {
        name: "TARDY Time Traveler",
        icons: ["tardytimetraveler"],
        id: "tardytimetraveler",
        munzee_id: 2365,
        duration: 4,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual)],
      },
    ],
  },
  {
    name: "Boomerangs 2020",
    id: "boomerangs2020",
    starts: "2020-01-24T10:00:00-06:00",
    ends: "2020-02-08T23:59:00-06:00",
    specials: [
      {
        name: "Coral Catcher Boomerang",
        icons: ["coralcatcherboomerang"],
        id: "coralcatcherboomerang",
        munzee_id: 2346,
        duration: 6,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "airmystery"],
      },
      {
        name: "Sunsetter Boomerang",
        icons: ["sunsetterboomerang"],
        id: "sunsetterboomerang",
        munzee_id: 2345,
        duration: 6,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "airmystery"],
      },
      {
        name: "Parting Sea Boomerang",
        icons: ["partingseaboomerang"],
        id: "partingseaboomerang",
        munzee_id: 2344,
        duration: 6,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "airmystery"],
      },
      {
        name: "Great Dividing Boomerang",
        icons: ["greatdividingboomerang"],
        id: "greatdividingboomerang",
        munzee_id: 2343,
        duration: 6,
        lands_on: ["munzee", "earthmystery"],
      },
      {
        name: "Country Crawler Boomerang",
        icons: ["countrycrawlerboomerang"],
        id: "countrycrawlerboomerang",
        munzee_id: 2342,
        duration: 6,
        lands_on: ["munzee", "earthmystery"],
      },
      {
        name: "Root Runner Boomerang",
        icons: ["rootrunnerboomerang"],
        id: "rootrunnerboomerang",
        munzee_id: 2341,
        duration: 6,
        lands_on: ["munzee", "earthmystery"],
      },
    ],
  },
];

export default s2020;
