import { SeasonalCategory } from ".";
import { TypeHidden, TypeState, TypeTags } from "@cuppazee/db";

const s2021: SeasonalCategory[] = [
  {
    name: "World Bicycle Day 2021",
    id: "worldbicycleday2021",
    starts: "2021-06-02T12:00:00-05:00",
    ends: "2021-06-30T23:59:00-05:00",
    pobs: [
      {
        name: "Champion Chopper",
        icons: ["championchopper"],
        id: "championchopper",
        lands_on: ["munzee", "shamrock", "firemystery", "pinkdiamond", "tractor"],
      },
      {
        name: "Unicorn Unicycle",
        icons: ["unicornunicycle"],
        id: "unicornunicycle",
        lands_on: ["munzee", "shamrock", "firemystery", "pinkdiamond", "tractor"],
      },
      {
        name: "Toy Trike",
        icons: ["toytrike"],
        id: "toytrike",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "flatlou",
          "poitransportation",
          i => i.meta.evolution_base === "firstwheel",
        ],
      },
      {
        name: "Bicentennial Bicycle",
        icons: ["bicentennialbicycle"],
        id: "bicentennialbicycle",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "flatlou",
          "poitransportation",
          i => i.meta.evolution_base === "firstwheel",
        ],
      },
      {
        name: "Tandem Twins",
        icons: ["tandemtwins"],
        id: "tandemtwins",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "flatlou",
          "poitransportation",
          i => i.meta.evolution_base === "firstwheel",
        ],
      },
    ],
    types: [
      {
        name: "Starting Line",
        icons: ["startingline"],
        id: "startingline",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Midway",
        icons: ["Midway"],
        id: "midway",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      ...["1st", "2nd", "3rd"].map(i => [
        {
          name: i + " Place Bicentennial Bicycle",
          icons: [i+"placebicentennialbicycle"],
          id: i+"placebicentennialbicycle",
          state: TypeState.Virtual,
          tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
          hidden: [TypeHidden.Inventory],
          meta: {
            scatter_duration: 2,
          },
        },
        {
          name: i + " Place Toy Trike",
          icons: [i+"placetoytrike"],
          id: i+"placetoytrike",
          state: TypeState.Virtual,
          tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
          hidden: [TypeHidden.Inventory],
          meta: {
            scatter_duration: 2,
          },
        },
        {
          name: i + " Place Champion Chopper",
          icons: [i+"placechampionchopper"],
          id: i+"placechampionchopper",
          state: TypeState.Virtual,
          tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
          hidden: [TypeHidden.Inventory],
          meta: {
            scatter_duration: 2,
          },
        },
        {
          name: i + " Place Unicorn Unicycle",
          icons: [i+"placeunicornunicycle"],
          id: i+"placeunicornunicycle",
          state: TypeState.Virtual,
          tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
          hidden: [TypeHidden.Inventory],
          meta: {
            scatter_duration: 2,
          },
        },
        {
          name: i + " Place Tandem Twins",
          icons: [i+"placetandemtwins"],
          id: i+"placetandemtwins",
          state: TypeState.Virtual,
          tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
          hidden: [TypeHidden.Inventory],
          meta: {
            scatter_duration: 2,
          },
        },
        {
          name: i + " Place Flat Lou",
          icons: [i+"placeflatlou"],
          id: i+"placelfatlou",
          state: TypeState.Virtual,
          tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
          hidden: [TypeHidden.Inventory],
          meta: {
            scatter_duration: 2,
          },
        },
      ]).flat()
    ]
  },
  {
    name: "Baby Panda",
    id: "babypanda2021",
    starts: "2021-05-21T12:00:00-05:00",
    ends: "2021-07-20T23:59:00-05:00",
    pobs: [
      {
        name: "Baby Panda",
        icons: ["babypanda"],
        id: "babypanda",
        lands_on: [],
      },
      {
        name: "Albino Baby Panda",
        icons: ["albinobabypanda"],
        id: "albinobabypanda",
        lands_on: [],
      },
    ],
  },
  {
    name: "Lost Socks",
    id: "lostsocks2021",
    starts: "2021-05-03T12:00:00-05:00",
    ends: "2021-05-31T23:59:00-05:00",
    specials: [
      {
        name: "Left Ankle Sock",
        icons: ["leftanklesock"],
        id: "leftanklesock",
        lands_on: [
          "munzee",
          "mystery",
          "urbanfit",
          i => i.has_tag(TypeTags.TypeGaming) && i.state === TypeState.Physical,
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
        ],
      },
      {
        name: "Left Argyle Sock",
        icons: ["leftargylesock"],
        id: "leftargylesock",
        lands_on: [
          "munzee",
          "mystery",
          "urbanfit",
          i => i.has_tag(TypeTags.TypeGaming) && i.state === TypeState.Physical,
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
        ],
      },
      {
        name: "Left Hole-y Sock",
        icons: ["lefthole-ysock"],
        id: "lefthole-ysock",
        lands_on: [
          "munzee",
          "mystery",
          "urbanfit",
          i => i.has_tag(TypeTags.TypeGaming) && i.state === TypeState.Physical,
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
        ],
      },
      {
        name: "Left Honeycomb Sock",
        icons: ["lefthoneycombsock"],
        id: "lefthoneycombsock",
        lands_on: [
          "munzee",
          "mystery",
          "urbanfit",
          i => i.has_tag(TypeTags.TypeGaming) && i.state === TypeState.Physical,
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
        ],
      },
      {
        name: "Left Striped Sock",
        icons: ["leftstripedsock"],
        id: "leftstripedsock",
        lands_on: [
          "munzee",
          "mystery",
          "urbanfit",
          i => i.has_tag(TypeTags.TypeGaming) && i.state === TypeState.Physical,
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
        ],
      },
      {
        name: "Left Toe Sock",
        icons: ["lefttoesock"],
        id: "lefttoesock",
        lands_on: [
          "munzee",
          "mystery",
          "urbanfit",
          i => i.has_tag(TypeTags.TypeGaming) && i.state === TypeState.Physical,
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
        ],
      },
      {
        name: "Left Tube Sock",
        icons: ["lefttubesock"],
        id: "lefttubesock",
        lands_on: [
          "munzee",
          "mystery",
          "urbanfit",
          i => i.has_tag(TypeTags.TypeGaming) && i.state === TypeState.Physical,
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
        ],
      },
      {
        name: "Left Unicorn Sock",
        icons: ["leftunicornsock"],
        id: "leftunicornsock",
        lands_on: [
          "munzee",
          "mystery",
          "urbanfit",
          i => i.has_tag(TypeTags.TypeGaming) && i.state === TypeState.Physical,
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
        ],
      },
      {
        name: "Right Ankle Sock",
        icons: ["rightanklesock"],
        id: "rightanklesock",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "poisports",
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
          "farmer",
          "farmerandwife",
          "family",
          "pottedplant",
          "garden",
          "field",
        ],
      },
      {
        name: "Right Argyle Sock",
        icons: ["rightargylesock"],
        id: "rightargylesock",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "poisports",
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
          "farmer",
          "farmerandwife",
          "family",
          "pottedplant",
          "garden",
          "field",
        ],
      },
      {
        name: "Right Hole-y Sock",
        icons: ["righthole-ysock"],
        id: "righthole-ysock",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "poisports",
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
          "farmer",
          "farmerandwife",
          "family",
          "pottedplant",
          "garden",
          "field",
        ],
      },
      {
        name: "Right Honeycomb Sock",
        icons: ["righthoneycombsock"],
        id: "righthoneycombsock",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "poisports",
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
          "farmer",
          "farmerandwife",
          "family",
          "pottedplant",
          "garden",
          "field",
        ],
      },
      {
        name: "Right Striped Sock",
        icons: ["rightstripedsock"],
        id: "rightstripedsock",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "poisports",
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
          "farmer",
          "farmerandwife",
          "family",
          "pottedplant",
          "garden",
          "field",
        ],
      },
      {
        name: "Right Toe Sock",
        icons: ["righttoesock"],
        id: "righttoesock",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "poisports",
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
          "farmer",
          "farmerandwife",
          "family",
          "pottedplant",
          "garden",
          "field",
        ],
      },
      {
        name: "Right Tube Sock",
        icons: ["righttubesock"],
        id: "righttubesock",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "poisports",
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
          "farmer",
          "farmerandwife",
          "family",
          "pottedplant",
          "garden",
          "field",
        ],
      },
      {
        name: "Right Unicorn Sock",
        icons: ["rightunicornsock"],
        id: "rightunicornsock",
        lands_on: [
          i => i.has_tag(TypeTags.TypeVirtual),
          "poisports",
          i => i.has_tag(TypeTags.TypeMysteryElemental) && i.state === TypeState.Physical,
          "farmer",
          "farmerandwife",
          "family",
          "pottedplant",
          "garden",
          "field",
        ],
      },
    ],
  },
  {
    name: "Baby Animals",
    id: "babyanimals2021",
    starts: "2021-04-01T00:00:00-05:00",
    ends: "2021-05-31T23:59:00-05:00",
    pobs: [
      {
        name: "Doge Pup",
        icons: ["dogepup"],
        id: "dogepup",
        lands_on: [],
      },
      {
        name: "Itty Bitty Kitty",
        icons: ["ittybittykitty"],
        id: "ittybittykitty",
        lands_on: [],
      },
      {
        name: "Baby Monkey",
        icons: ["babymonkey"],
        id: "babymonkey",
        lands_on: [],
      },
    ],
  },
  {
    name: "April Fools",
    id: "aprilfools2021",
    starts: "2021-04-01T12:00:00-05:00",
    ends: "2021-04-30T23:59:00-05:00",
    specials: [
      {
        name: "Bag of Tricks",
        icons: ["bagoftricks"],
        id: "bagoftricks",
        lands_on: [],
      },
      {
        name: "Sack of Surprises",
        icons: ["sackofsurprises"],
        id: "sackofsurprises",
        lands_on: [],
      },
    ],
    types: [
      {
        name: "Squirting Flower",
        icons: ["squirtingflower"],
        id: "squirtingflower",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Sneezing Powder",
        icons: ["sneezingpowder"],
        id: "sneezingpowder",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Can of Snakes",
        icons: ["canofsnakes"],
        id: "canofsnakes",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Spider Gum",
        icons: ["spidergum"],
        id: "spidergum",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Whoopee Cushion",
        icons: ["whoopeecushion"],
        id: "whoopeecushion",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Buzzer Ring",
        icons: ["buzzerring"],
        id: "buzzerring",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
    ],
  },
  {
    name: "Jack in Zee Box",
    id: "jackinzeebox",
    starts: "2021-03-31T12:00:00-05:00",
    ends: "2021-05-11T23:59:00-05:00",
    pobs: [
      {
        name: "Jack in Zee Box",
        icons: ["jackinzeebox"],
        id: "jackinzeebox",
        lands_on: [],
      },
      {
        name: "Applejack in Zee Box",
        icons: ["jackinzeebox-applejackinthebox"],
        id: "jackinzeebox-applejackinthebox",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Blast in Zee Box",
        icons: ["jackinzeebox-blastinthebox"],
        id: "jackinzeebox-blastinthebox",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Boxing Glove",
        icons: ["jackinzeebox-boxingglove"],
        id: "jackinzeebox-boxingglove",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Fire Prankster",
        icons: ["jackinzeebox-fireprankster"],
        id: "jackinzeebox-fireprankster",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "High Five",
        icons: ["jackinzeebox-highfive"],
        id: "jackinzeebox-highfive",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Ice Prankster",
        icons: ["jackinzeebox-iceprankster"],
        id: "jackinzeebox-iceprankster",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Prankster",
        icons: ["jackinzeebox-prankster"],
        id: "jackinzeebox-prankster",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "ROBblehead",
        icons: ["jackinzeebox-robblehead"],
        id: "jackinzeebox-robblehead",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Unicorn",
        icons: ["jackinzeebox-unicorn"],
        id: "jackinzeebox-unicorn",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
      {
        name: "Zack in The Box",
        icons: ["jackinzeebox-zackinthebox"],
        id: "jackinzeebox-zackinthebox",
        lands_on: [],
        hidden: [TypeHidden.Bouncers],
      },
    ],
  },
  {
    name: "Zee Folk",
    id: "zeefolk2020",
    starts: "2021-03-17T00:00:00-05:00",
    ends: "2021-03-31T23:59:00-05:00",
    specials: [
      {
        name: "Zee Folk",
        icons: ["zeefolk"],
        id: "zeefolk",
        lands_on: [],
      },
    ],
  },
  {
    name: "Women's History Month",
    id: "womenshistory2020",
    starts: "2021-02-25T12:00:00-05:00",
    ends: "2021-03-14T23:59:00-05:00",
    specials: [
      {
        name: "Amelia Earhart",
        icons: ["ameliaearhart"],
        id: "ameliaearhart",
        lands_on: ["munzee", "mystery"],
      },
      {
        name: "Frida Kahlo",
        icons: ["fridakahlo"],
        id: "fridakahlo",
        lands_on: [
          "munzee",
          type =>
            type.has_tag(TypeTags.EvolutionNature) &&
            ["roseseed", "tulipseed", "lilyseed"].includes(type.meta.evolution_base || ""),
        ],
      },
      {
        name: "Hedy Lamarr",
        icons: ["hedylamarr"],
        id: "hedylamarr",
        lands_on: [
          "munzee",
          type => type.has_tag(TypeTags.TypeJewel) && type.state === TypeState.Physical,
        ],
      },
      {
        name: "Maya Angelou",
        icons: ["mayaangelou"],
        id: "mayaangelou",
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "poilibrary", "surprise"],
      },
      {
        name: "Jane Goodall",
        icons: ["janegoodall"],
        id: "janegoodall",
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "poiwildlife",
          type => type.meta.evolution_base === "safaritruck",
        ],
      },
      {
        name: "Margaret Hamilton",
        icons: ["margarethamilton"],
        id: "margarethamilton",
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "poiuniqueattraction",
          "joystickvirtual",
        ],
      },
    ],
    types: [
      {
        name: "Flight Pin",
        icons: ["flightpin"],
        id: "flightpin",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Palette",
        icons: ["palette"],
        id: "palette",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Film Reel",
        icons: ["filmreel"],
        id: "filmreel",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Poem",
        icons: ["poem"],
        id: "poem",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Chimpanzee",
        icons: ["chimpanzee"],
        id: "chimpanzee",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Rocket",
        icons: ["rocket"],
        id: "rocket",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
    ],
  },
  {
    name: "Courier Critters",
    id: "couriercritters2020",
    starts: "2021-02-01T00:00:00-05:00",
    ends: "2021-04-31T23:59:00-05:00",
    pobs: [
      {
        name: "Courier Stork",
        icons: ["courierstork"],
        id: "courierstork",
        munzee_id: 2853,
        lands_on: [],
      },
      {
        name: "Courier Owl",
        icons: ["courierowl"],
        id: "courierowl",
        munzee_id: 2854,
        lands_on: [],
      },
      {
        name: "Courier Pigeon",
        icons: ["courierpigeon"],
        id: "courierpigeon",
        munzee_id: 2855,
        lands_on: [],
      },
    ],
  },
  {
    name: "Special Delivery Cupid",
    id: "specialdeliverycupid2021",
    starts: "2021-02-01T00:00:00-06:00",
    ends: "2021-02-28T23:59:00-06:00",
    pobs: [
      {
        name: "Special Delivery Cupid",
        icons: ["specialdeliverycupid"],
        id: "specialdeliverycupid",
        munzee_id: 2851,
        duration: 5,
        lands_on: [
          "treehouse",
          "skyland",
          "munzee",
          "firemystery",
          "airmystery",
          "poipostoffice",
          type => type.has_tag(TypeTags.TypeVirtual),
          type => type.has_tag(TypeTags.TypeReseller),
          type => type.has_tag(TypeTags.TypeSeasonal),
        ],
      },
    ],
    types: [
      {
        name: "Heart Arrow",
        icons: ["heartarrow"],
        id: "heartarrow",
        munzee_id: 2852,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
    ],
  },
  {
    name: "Buzzle Box",
    id: "buzzlebox2021",
    starts: "2021-01-29T00:00:00-06:00",
    ends: "2021-02-21T23:59:00-06:00",
    specials: [
      {
        name: "Buzzle Box",
        icons: ["buzzlebox"],
        id: "buzzlebox",
        munzee_id: 2856,
        duration: 6,
        lands_on: [
          "munzee",
          "joystick",
          type => type.has_tag(TypeTags.TypeMystery) && type.state === TypeState.Physical,
        ],
      },
    ],
    types: [
      {
        name: "Red Buzzle Piece 1",
        icons: ["redbuzzlepiece1"],
        id: "redbuzzlepiece1",
        munzee_id: 2857,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Red Buzzle Piece 2",
        icons: ["redbuzzlepiece2"],
        id: "redbuzzlepiece2",
        munzee_id: 2858,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Red Buzzle Piece 3",
        icons: ["redbuzzlepiece3"],
        id: "redbuzzlepiece3",
        munzee_id: 2859,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Red Buzzle Piece 4",
        icons: ["redbuzzlepiece4"],
        id: "redbuzzlepiece4",
        munzee_id: 2860,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Green Buzzle Piece 1",
        icons: ["greenbuzzlepiece1"],
        id: "greenbuzzlepiece1",
        munzee_id: 2861,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Green Buzzle Piece 2",
        icons: ["greenbuzzlepiece2"],
        id: "greenbuzzlepiece2",
        munzee_id: 2862,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Green Buzzle Piece 3",
        icons: ["greenbuzzlepiece3"],
        id: "greenbuzzlepiece3",
        munzee_id: 2863,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Green Buzzle Piece 4",
        icons: ["greenbuzzlepiece4"],
        id: "greenbuzzlepiece4",
        munzee_id: 2864,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Yellow Buzzle Piece 1",
        icons: ["yellowbuzzlepiece1"],
        id: "yellowbuzzlepiece1",
        munzee_id: 2865,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Yellow Buzzle Piece 2",
        icons: ["yellowbuzzlepiece2"],
        id: "yellowbuzzlepiece2",
        munzee_id: 2866,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Yellow Buzzle Piece 3",
        icons: ["yellowbuzzlepiece3"],
        id: "yellowbuzzlepiece3",
        munzee_id: 2867,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Yellow Buzzle Piece 4",
        icons: ["yellowbuzzlepiece4"],
        id: "yellowbuzzlepiece4",
        munzee_id: 2868,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
    ],
  },
  {
    name: "Hamilton Hamzee",
    id: "hamiltonhamzee2021",
    starts: "2021-01-21T00:00:00-06:00",
    ends: "2021-03-15T23:59:00-06:00",
    pobs: [
      {
        name: "Hamilton Hamzee",
        icons: ["hamiltonhamzee"],
        id: "hamiltonhamzee",
        munzee_id: 2850,
        duration: 6,
        lands_on: [
          "treehouse",
          "munzee",
          "earthmystery",
          "icemystery",
          type => type.has_tag(TypeTags.TypeSeasonal),
        ],
      },
    ],
  },
  {
    name: "Garden Gnomes",
    id: "gnomes2021",
    starts: "2021-01-01T00:00:00-06:00",
    ends: "2021-12-31T23:59:00-06:00",
    pobs: [
      {
        name: "Garden Gnome",
        icons: ["gardengnome"],
        id: "gardengnome",
        munzee_id: 2775,
        duration: 6,
        lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "munzee"],
      },
      {
        name: "Ice Hockey Garden Gnome",
        icons: ["icehockeygardengnome"],
        id: "icehockeygardengnome",
        munzee_id: 2776,
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          "icemystery",
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "Archery Garden Gnome",
        icons: ["archerygardengnome"],
        id: "archerygardengnome",
        munzee_id: 2777,
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          "crossbow",
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "Basketball Garden Gnome",
        icons: ["basketballgardengnome"],
        id: "basketballgardengnome",
        munzee_id: 2778,
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          "airmystery",
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "Running Garden Gnome",
        icons: ["runninggardengnome"],
        id: "runninggardengnome",
        munzee_id: 2779,
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          "urbanfit",
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "Aussie Explorer Garden Gnome",
        icons: ["aussieexplorergardengnome"],
        id: "aussieexplorergardengnome",
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          type => type.has_tag(TypeTags.TypeReseller) && !type.has_tag(TypeTags.Scatter),
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "Gold Miner Garden Gnome",
        icons: ["goldminergardengnome"],
        id: "goldminergardengnome",
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          type => type.has_tag(TypeTags.TypeReseller) && !type.has_tag(TypeTags.Scatter),
          "treehouse",
          "skyland",
          "coin",
          "bagofcoins",
          "treasurechest",
        ],
      },
      {
        name: "Queen's Guardsman Garden Gnome",
        icons: ["queen'sguardsmangardengnome"],
        id: "queen'sguardsmangardengnome",
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          type => type.has_tag(TypeTags.TypeReseller) && !type.has_tag(TypeTags.Scatter),
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "Astronaut Garden Gnome",
        icons: ["astronautgardengnome"],
        id: "astronautgardengnome",
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          type => type.has_tag(TypeTags.TypeReseller) && !type.has_tag(TypeTags.Scatter),
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "Soccer Garden Gnome",
        icons: ["soccergardengnome"],
        id: "soccergardengnome",
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          "virtualonyx",
          "treehouse",
          "skyland",
        ],
      },
      {
        name: "Skateboarding Garden Gnome",
        icons: ["skateboardinggardengnome"],
        id: "skateboardinggardengnome",
        duration: 6,
        lands_on: [
          type => type.has_tag(TypeTags.TypeVirtual),
          "munzee",
          "poiplaypark",
          "treehouse",
          "skyland",
        ],
      },
    ],
    types: [
      {
        name: "Gnome Hockey Helmet",
        icons: ["gnomehockeyhelmet"],
        id: "gnomehockeyhelmet",
        munzee_id: 2802,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Gnome Archery Hood",
        icons: ["gnomearcheryhood"],
        id: "gnomearcheryhood",
        munzee_id: 2803,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Gnome Noggin Net",
        icons: ["gnomenogginnet"],
        id: "gnomenogginnet",
        munzee_id: 2804,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Gnome Miner Hat",
        icons: ["gnomeminerhat"],
        id: "gnomeminerhat",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Gnome Explorer Hat",
        icons: ["gnomeexplorerhat"],
        id: "gnomeexplorerhat",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Gnome Bear Skin Hat",
        icons: ["gnomebearskinhat"],
        id: "gnomebearskinhat",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Gnome Astronaut Helmet",
        icons: ["gnomeastronauthelmet"],
        id: "gnomeastronauthelmet",
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Gnome Headphones",
        icons: ["gnomeheadphones"],
        id: "gnomeheadphones",
        munzee_id: 2805,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Gnome Header Hat",
        icons: ["gnomeheaderhat"],
        id: "gnomeheaderhat",
        munzee_id: 2806,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
      {
        name: "Gnome Heelflip Hat",
        icons: ["gnomeheelfliphat"],
        id: "gnomeheelfliphat",
        munzee_id: 2807,
        state: TypeState.Virtual,
        tags: [TypeTags.ScatterStandalone, TypeTags.Scatter],
        hidden: [TypeHidden.Inventory],
        meta: {
          scatter_duration: 2,
        },
      },
    ],
  },
];

export default s2021;
