import {
  TypePoints,
  TypePointsType,
  TypeHidden,
  TypeState,
  TypeTags,
} from "@cuppazee/db";

const misc: {
  name: string;
  icons: string[];
  id: string;
  munzee_id?: number;
  state: TypeState;
  tags?: TypeTags[];
  hidden?: TypeHidden[];
  points?: TypePoints;
}[] = [
  {
    name: "Greenie",
    icons: ["munzee", "greenie", "normal", "standard"],
    id: "munzee",
    munzee_id: 0,
    state: TypeState.Physical,
    points: {
      deploy: 19,
      capture: 20,
      capon: 11,
    },
  },
  {
    name: "Premium",
    icons: ["premium"],
    id: "premium",
    munzee_id: 13,
    state: TypeState.Physical,
    points: {
      deploy: 200,
      capon: 50,
      capture: 50,
    },
  },
  {
    name: "Social",
    icons: ["social"],
    id: "social",
    munzee_id: 32,
    state: TypeState.Locationless,
    tags: [TypeTags.TypeSocial],
    hidden: [TypeHidden.Inventory],
  },
  {
    name: "Event Pin",
    icons: ["eventpin"],
    id: "eventpin",
    munzee_id: 60,
    state: TypeState.Physical,
    tags: [TypeTags.TypeEvent, TypeTags.TypeEventStandard],
    hidden: [TypeHidden.Inventory],
  },
  {
    name: "Trail Munzee",
    icons: ["trail"],
    id: "trail",
    munzee_id: 190,
    state: TypeState.Physical,
    tags: [TypeTags.TypeTrail],
  },
  {
    name: "Personal Munzee",
    icons: ["personalmunzee"],
    id: "personalmunzee",
    munzee_id: 200,
    state: TypeState.Locationless,
    tags: [TypeTags.TypePersonal],
    points: {
      deploy: 10,
      type: TypePointsType.Split,
      split: 50,
      min: 10,
    },
    hidden: [TypeHidden.Inventory],
  },
  {
    name: "Event Indicator",
    icons: ["eventindicator"],
    id: "eventindicator",
    munzee_id: 294,
    state: TypeState.Physical,
    tags: [TypeTags.TypeEvent, TypeTags.TypeEventStandard],
    hidden: [TypeHidden.Inventory],
  },
  {
    name: "Virtual Trail",
    icons: ["virtual_trail"],
    id: "virtual_trail",
    munzee_id: 390,
    state: TypeState.Virtual,
    tags: [TypeTags.TypeTrail],
  },
  {
    name: "Shamrock",
    icons: ["shamrock"],
    id: "shamrock",
    munzee_id: 441,
    state: TypeState.Physical,
  },
  {
    name: "Event Trail",
    icons: ["eventtrail"],
    id: "eventtrail",
    munzee_id: 600,
    tags: [TypeTags.TypeEvent, TypeTags.TypeEventStandard, TypeTags.TypeTrail],
    state: TypeState.Virtual,
    hidden: [TypeHidden.Inventory],
  },
  {
    name: "Premium Personal",
    icons: ["premiumpersonal"],
    id: "premiumpersonal",
    munzee_id: 1107,
    state: TypeState.Locationless,
    tags: [TypeTags.TypePersonal],
    points: {
      deploy: 25,
      type: TypePointsType.Split,
      split: 100,
      min: 20,
    },
    hidden: [TypeHidden.Inventory],
  },
  {
    name: "Spring Seasonal",
    icons: ["springseasonalmunzee"],
    id: "springseasonalmunzee",
    munzee_id: 1135,
    state: TypeState.Physical,
    tags: [TypeTags.TypeSeasonal],
    hidden: [TypeHidden.Inventory],
  },
  {
    name: "Summer Seasonal",
    icons: ["summerseasonalmunzee"],
    id: "summerseasonalmunzee",
    munzee_id: 1136,
    state: TypeState.Physical,
    tags: [TypeTags.TypeSeasonal],
    hidden: [TypeHidden.Inventory],
  },
  {
    name: "Fall Seasonal",
    icons: ["fallseasonalmunzee"],
    id: "fallseasonalmunzee",
    munzee_id: 1137,
    state: TypeState.Physical,
    tags: [TypeTags.TypeSeasonal],
    hidden: [TypeHidden.Inventory],
  },
  {
    name: "Winter Seasonal",
    icons: ["winterseasonalmunzee"],
    id: "winterseasonalmunzee",
    munzee_id: 1138,
    state: TypeState.Physical,
    tags: [TypeTags.TypeSeasonal],
    hidden: [TypeHidden.Inventory],
  },
  {
    name: "Seasonal",
    icons: ["seasonal"],
    id: "seasonal",
    munzee_id: 1139,
    state: TypeState.Physical,
    tags: [TypeTags.TypeSeasonal],
    hidden: [TypeHidden.Capture, TypeHidden.Deploy],
  },
  {
    name: "Temporary Virtual",
    icons: ["temporaryvirtual", "tempvirt"],
    id: "temporaryvirtual",
    munzee_id: 1245,
    state: TypeState.Virtual,
    points: {
      deploy: 30,
      type: TypePointsType.Split,
      split: 75,
      min: 25,
    },
  },
  {
    name: "QRewzee",
    icons: ["qrewzee"],
    id: "qrewzee",
    munzee_id: 1880,
    state: TypeState.Physical,
    hidden: [TypeHidden.Inventory, TypeHidden.Deploy],
  },
  {
    name: "Renovation",
    icons: ["renovation"],
    id: "renovation",
    munzee_id: 2390,
    state: TypeState.Locationless,
    hidden: [TypeHidden.Inventory, TypeHidden.Deploy],
  },
  {
    name: "SleepZee",
    icons: ["sleepzee"],
    id: "sleepzee",
    munzee_id: 2744,
    state: TypeState.Virtual,
    hidden: [TypeHidden.Inventory, TypeHidden.Deploy],
  },
  {
    name: "Virtual Shamrock",
    icons: ["virtualshamrock"],
    id: "virtualshamrock",
    state: TypeState.Virtual,
  },
];

export default misc;