import { TypeTags } from "@cuppazee/db";

const virtuals: {
  name: string;
  icons: string[];
  id: string;
  munzee_id?: number;
  virtual_colors?: TypeTags[];
}[] = [
  {
    name: "Virtual",
    icons: ["virtual"],
    id: "virtual",
    munzee_id: 1409,
  },
  {
    name: "Virtual Rainbow",
    icons: ["virtual_rainbow"],
    id: "virtual_rainbow",
    munzee_id: 1410,
  },
  {
    name: "Virtual Timberwolf",
    icons: ["virtual_timberwolf"],
    id: "virtual_timberwolf",
    munzee_id: 1411,
    virtual_colors: [TypeTags.VirtualColourBlack],
  },
  {
    name: "Virtual Silver",
    icons: ["virtual_silver"],
    id: "virtual_silver",
    munzee_id: 1412,
    virtual_colors: [TypeTags.VirtualColourBlack],
  },
  {
    name: "Virtual Gray",
    icons: ["virtual_gray"],
    id: "virtual_gray",
    munzee_id: 1413,
    virtual_colors: [TypeTags.VirtualColourBlack],
  },
  {
    name: "Virtual Black",
    icons: ["virtual_black"],
    id: "virtual_black",
    munzee_id: 1414,
    virtual_colors: [TypeTags.VirtualColourBlack],
  },
  {
    name: "Virtual Orchid",
    icons: ["virtual_orchid"],
    id: "virtual_orchid",
    munzee_id: 1415,
    virtual_colors: [TypeTags.VirtualColourPink],
  },
  {
    name: "Virtual Wisteria",
    icons: ["virtual_wisteria"],
    id: "virtual_wisteria",
    munzee_id: 1416,
  },
  {
    name: "Virtual Purple Mountains Majesty",
    icons: ["virtual_purple_mountains_majesty"],
    id: "virtual_purple_mountains_majesty",
    munzee_id: 1417,
  },
  {
    name: "Virtual Violet",
    icons: ["virtual_violet"],
    id: "virtual_violet",
    munzee_id: 1418,
  },
  {
    name: "Virtual Plum",
    icons: ["virtual_plum"],
    id: "virtual_plum",
    munzee_id: 1419,
  },
  {
    name: "Virtual Blue Violet",
    icons: ["virtual_blue_violet"],
    id: "virtual_blue_violet",
    munzee_id: 1420,
    virtual_colors: [TypeTags.VirtualColourBlue],
  },
  {
    name: "Virtual Blue",
    icons: ["virtual_blue"],
    id: "virtual_blue",
    munzee_id: 1421,
    virtual_colors: [TypeTags.VirtualColourBlue],
  },
  {
    name: "Virtual Cadet Blue",
    icons: ["virtual_cadet_blue"],
    id: "virtual_cadet_blue",
    munzee_id: 1423,
    virtual_colors: [TypeTags.VirtualColourBlue],
  },
  {
    name: "Virtual Periwinkle",
    icons: ["virtual_periwinkle"],
    id: "virtual_periwinkle",
    munzee_id: 1424,
    virtual_colors: [TypeTags.VirtualColourBlue],
  },
  {
    name: "Virtual Cornflower",
    icons: ["virtual_cornflower"],
    id: "virtual_cornflower",
    munzee_id: 1425,
    virtual_colors: [TypeTags.VirtualColourBlue],
  },
  {
    name: "Virtual Blue Green",
    icons: ["virtual_blue_green"],
    id: "virtual_blue_green",
    munzee_id: 1426,
    virtual_colors: [TypeTags.VirtualColourBlue],
  },
  {
    name: "Virtual Pacific Blue",
    icons: ["virtual_pacific_blue"],
    id: "virtual_pacific_blue",
    munzee_id: 1427,
    virtual_colors: [TypeTags.VirtualColourBlue],
  },
  {
    name: "Virtual Cerulean",
    icons: ["virtual_cerulean"],
    id: "virtual_cerulean",
    munzee_id: 1428,
    virtual_colors: [TypeTags.VirtualColourBlue],
  },
  {
    name: "Virtual Robin Egg Blue",
    icons: ["virtual_robin_egg_blue"],
    id: "virtual_robin_egg_blue",
    munzee_id: 1429,
    virtual_colors: [TypeTags.VirtualColourBlue],
  },
  {
    name: "Virtual Indigo",
    icons: ["virtual_indigo"],
    id: "virtual_indigo",
    munzee_id: 1430,
    virtual_colors: [TypeTags.VirtualColourBlue],
  },
  {
    name: "Virtual Turquoise Blue",
    icons: ["virtual_turquoise_blue"],
    id: "virtual_turquoise_blue",
    munzee_id: 1431,
    virtual_colors: [TypeTags.VirtualColourBlue],
  },
  {
    name: "Virtual Sea Green",
    icons: ["virtual_sea_green"],
    id: "virtual_sea_green",
    munzee_id: 1432,
    virtual_colors: [TypeTags.VirtualColourGreen],
  },
  {
    name: "Virtual Granny Smith Apple",
    icons: ["virtual_granny_smith_apple"],
    id: "virtual_granny_smith_apple",
    munzee_id: 1433,
    virtual_colors: [TypeTags.VirtualColourGreen],
  },
  {
    name: "Virtual Green",
    icons: ["virtual_green"],
    id: "virtual_green",
    munzee_id: 1434,
    virtual_colors: [TypeTags.VirtualColourGreen],
  },
  {
    name: "Virtual Forest Green",
    icons: ["virtual_forest_green"],
    id: "virtual_forest_green",
    munzee_id: 1435,
    virtual_colors: [TypeTags.VirtualColourGreen],
  },
  {
    name: "Virtual Asparagus",
    icons: ["virtual_asparagus"],
    id: "virtual_asparagus",
    munzee_id: 1436,
    virtual_colors: [TypeTags.VirtualColourGreen],
  },
  {
    name: "Virtual Olive Green",
    icons: ["virtual_olive_green"],
    id: "virtual_olive_green",
    munzee_id: 1437,
    virtual_colors: [TypeTags.VirtualColourGreen],
  },
  {
    name: "Virtual Yellow Green",
    icons: ["virtual_yellow_green"],
    id: "virtual_yellow_green",
    munzee_id: 1438,
    virtual_colors: [TypeTags.VirtualColourGreen],
  },
  {
    name: "Virtual Green Yellow",
    icons: ["virtual_green_yellow"],
    id: "virtual_green_yellow",
    munzee_id: 1439,
    virtual_colors: [TypeTags.VirtualColourGreen],
  },
  {
    name: "Virtual Spring Green",
    icons: ["virtual_spring_green"],
    id: "virtual_spring_green",
    munzee_id: 1440,
    virtual_colors: [TypeTags.VirtualColourGreen],
  },
  {
    name: "Virtual Gold",
    icons: ["virtual_gold"],
    id: "virtual_gold",
    munzee_id: 1441,
  },
  {
    name: "Virtual Yellow",
    icons: ["virtual_yellow"],
    id: "virtual_yellow",
    munzee_id: 1442,
  },
  {
    name: "Virtual Goldenrod",
    icons: ["virtual_goldenrod"],
    id: "virtual_goldenrod",
    munzee_id: 1443,
  },
  {
    name: "Virtual Dandelion",
    icons: ["virtual_dandelion"],
    id: "virtual_dandelion",
    munzee_id: 1444,
  },
  {
    name: "Virtual Orange",
    icons: ["virtual_orange"],
    id: "virtual_orange",
    munzee_id: 1445,
  },
  {
    name: "Virtual Burnt Orange",
    icons: ["virtual_burnt_orange"],
    id: "virtual_burnt_orange",
    munzee_id: 1446,
  },
  {
    name: "Virtual Melon",
    icons: ["virtual_melon"],
    id: "virtual_melon",
    munzee_id: 1448,
    virtual_colors: [TypeTags.VirtualColourPink],
  },
  {
    name: "Virtual Pink",
    icons: ["virtual_pink"],
    id: "virtual_pink",
    munzee_id: 1449,
    virtual_colors: [TypeTags.VirtualColourPink, TypeTags.VirtualColourLouPink],
  },
  {
    name: "Virtual Carnation Pink",
    icons: ["virtual_carnation_pink"],
    id: "virtual_carnation_pink",
    munzee_id: 1450,
    virtual_colors: [TypeTags.VirtualColourPink, TypeTags.VirtualColourLouPink],
  },
  {
    name: "Virtual Mauvelous",
    icons: ["virtual_mauvelous"],
    id: "virtual_mauvelous",
    munzee_id: 1451,
    virtual_colors: [TypeTags.VirtualColourPink, TypeTags.VirtualColourLouPink],
  },
  {
    name: "Virtual Salmon",
    icons: ["virtual_salmon"],
    id: "virtual_salmon",
    munzee_id: 1452,
    virtual_colors: [TypeTags.VirtualColourPink, TypeTags.VirtualColourLouPink],
  },
  {
    name: "Virtual Tickle Me Pink",
    icons: ["virtual_tickle_me_pink"],
    id: "virtual_tickle_me_pink",
    munzee_id: 1453,
    virtual_colors: [TypeTags.VirtualColourPink, TypeTags.VirtualColourLouPink],
  },
  {
    name: "Virtual Magenta",
    icons: ["virtual_magenta"],
    id: "virtual_magenta",
    munzee_id: 1454,
    virtual_colors: [TypeTags.VirtualColourPink, TypeTags.VirtualColourLouPink],
  },
  {
    name: "Virtual Wild Strawberry",
    icons: ["virtual_wild_strawberry"],
    id: "virtual_wild_strawberry",
    munzee_id: 1455,
    virtual_colors: [TypeTags.VirtualColourPink, TypeTags.VirtualColourLouPink],
  },
  {
    name: "Virtual Violet Red",
    icons: ["virtual_violet_red"],
    id: "virtual_violet_red",
    munzee_id: 1456,
    virtual_colors: [TypeTags.VirtualColourPink, TypeTags.VirtualColourLouPink],
  },
  {
    name: "Virtual Red Violet",
    icons: ["virtual_red_violet"],
    id: "virtual_red_violet",
    munzee_id: 1457,
    virtual_colors: [TypeTags.VirtualColourPink, TypeTags.VirtualColourLouPink],
  },
  {
    name: "Virtual Apricot",
    icons: ["virtual_apricot"],
    id: "virtual_apricot",
    munzee_id: 1458,
  },
  {
    name: "Virtual Peach",
    icons: ["virtual_peach"],
    id: "virtual_peach",
    munzee_id: 1459,
  },
  {
    name: "Virtual Macaroni and Cheese",
    icons: ["virtual_macaroni_and_cheese"],
    id: "virtual_macaroni_and_cheese",
    munzee_id: 1460,
  },
  {
    name: "Virtual Tan",
    icons: ["virtual_tan"],
    id: "virtual_tan",
    munzee_id: 1461,
  },
  {
    name: "Virtual Burnt Sienna",
    icons: ["virtual_burnt_sienna"],
    id: "virtual_burnt_sienna",
    munzee_id: 1462,
  },
  {
    name: "Virtual Bittersweet",
    icons: ["virtual_bittersweet"],
    id: "virtual_bittersweet",
    munzee_id: 1463,
    virtual_colors: [TypeTags.VirtualColourRed],
  },
  {
    name: "Virtual Red Orange",
    icons: ["virtual_red_orange"],
    id: "virtual_red_orange",
    munzee_id: 1464,
    virtual_colors: [TypeTags.VirtualColourRed],
  },
  {
    name: "Virtual Scarlet",
    icons: ["virtual_scarlet"],
    id: "virtual_scarlet",
    munzee_id: 1465,
    virtual_colors: [TypeTags.VirtualColourRed],
  },
  {
    name: "Virtual Red",
    icons: ["virtual_red"],
    id: "virtual_red",
    munzee_id: 1466,
    virtual_colors: [TypeTags.VirtualColourRed],
  },
  {
    name: "Virtual Brick Red",
    icons: ["virtual_brick_red"],
    id: "virtual_brick_red",
    munzee_id: 1467,
    virtual_colors: [TypeTags.VirtualColourRed],
  },
  {
    name: "Virtual Mahogany",
    icons: ["virtual_mahogany"],
    id: "virtual_mahogany",
    munzee_id: 1468,
    virtual_colors: [TypeTags.VirtualColourRed, TypeTags.VirtualColourBrown],
  },
  {
    name: "Virtual Chestnut",
    icons: ["virtual_chestnut"],
    id: "virtual_chestnut",
    munzee_id: 1469,
    virtual_colors: [TypeTags.VirtualColourBrown],
  },
  {
    name: "Virtual Tumbleweed",
    icons: ["virtual_tumbleweed"],
    id: "virtual_tumbleweed",
    munzee_id: 1470,
    virtual_colors: [TypeTags.VirtualColourBrown],
  },
  {
    name: "Virtual Raw Sienna",
    icons: ["virtual_raw_sienna"],
    id: "virtual_raw_sienna",
    munzee_id: 1471,
    virtual_colors: [TypeTags.VirtualColourBrown],
  },
  {
    name: "Virtual Brown",
    icons: ["virtual_brown"],
    id: "virtual_brown",
    munzee_id: 1473,
    virtual_colors: [TypeTags.VirtualColourBrown],
  },
]

export default virtuals;