import { TypeState } from "@cuppazee/db";

const zodiacs: {
  name: string;
  icons: string[];
  id: string;
  munzee_id?: number;
  state: TypeState;
  zodiac: "western" | "chinese" | "egyptian";
}[] = [
  {
    name: "Scorpio",
    icons: ["scorpio"],
    id: "scorpio",
    munzee_id: 308,
    state: TypeState.Physical,
    zodiac: "western",
  },
  {
    name: "Sagittarius",
    icons: ["sagittarius"],
    id: "sagittarius",
    munzee_id: 312,
    state: TypeState.Physical,
    zodiac: "western",
  },
  {
    name: "Capricorn",
    icons: ["capricorn"],
    id: "capricorn",
    munzee_id: 313,
    state: TypeState.Physical,
    zodiac: "western",
  },
  {
    name: "Aquarius",
    icons: ["aquarius"],
    id: "aquarius",
    munzee_id: 314,
    state: TypeState.Physical,
    zodiac: "western",
  },
  {
    name: "Pisces",
    icons: ["pisces"],
    id: "pisces",
    munzee_id: 315,
    state: TypeState.Physical,
    zodiac: "western",
  },
  {
    name: "Aries",
    icons: ["aries"],
    id: "aries",
    munzee_id: 316,
    state: TypeState.Physical,
    zodiac: "western",
  },
  {
    name: "Taurus",
    icons: ["taurus"],
    id: "taurus",
    munzee_id: 317,
    state: TypeState.Physical,
    zodiac: "western",
  },
  {
    name: "Gemini",
    icons: ["gemini"],
    id: "gemini",
    munzee_id: 318,
    state: TypeState.Physical,
    zodiac: "western",
  },
  {
    name: "Cancer",
    icons: ["cancer"],
    id: "cancer",
    munzee_id: 319,
    state: TypeState.Physical,
    zodiac: "western",
  },
  {
    name: "Leo",
    icons: ["leo"],
    id: "leo",
    munzee_id: 320,
    state: TypeState.Physical,
    zodiac: "western",
  },
  {
    name: "Virgo",
    icons: ["virgo"],
    id: "virgo",
    munzee_id: 321,
    state: TypeState.Physical,
    zodiac: "western",
  },
  {
    name: "Libra",
    icons: ["libra"],
    id: "libra",
    munzee_id: 322,
    state: TypeState.Physical,
    zodiac: "western",
  },
  {
    name: "Dog Chinese Zodiac",
    icons: ["dogchinesezodiac"],
    id: "dogchinesezodiac",
    munzee_id: 1271,
    state: TypeState.Physical,
    zodiac: "chinese",
  },
  {
    name: "Pig Chinese Zodiac",
    icons: ["pigchinesezodiac"],
    id: "pigchinesezodiac",
    munzee_id: 1272,
    state: TypeState.Physical,
    zodiac: "chinese",
  },
  {
    name: "Rat Chinese Zodiac",
    icons: ["ratchinesezodiac"],
    id: "ratchinesezodiac",
    munzee_id: 1273,
    state: TypeState.Physical,
    zodiac: "chinese",
  },
  {
    name: "Ox Chinese Zodiac",
    icons: ["oxchinesezodiac"],
    id: "oxchinesezodiac",
    munzee_id: 1274,
    state: TypeState.Physical,
    zodiac: "chinese",
  },
  {
    name: "Tiger Chinese Zodiac",
    icons: ["tigerchinesezodiac"],
    id: "tigerchinesezodiac",
    munzee_id: 1275,
    state: TypeState.Physical,
    zodiac: "chinese",
  },
  {
    name: "Rabbit Chinese Zodiac",
    icons: ["rabbitchinesezodiac"],
    id: "rabbitchinesezodiac",
    munzee_id: 1276,
    state: TypeState.Physical,
    zodiac: "chinese",
  },
  {
    name: "Dragon Chinese Zodiac",
    icons: ["dragonchinesezodiac"],
    id: "dragonchinesezodiac",
    munzee_id: 1277,
    state: TypeState.Physical,
    zodiac: "chinese",
  },
  {
    name: "Snake Chinese Zodiac",
    icons: ["snakechinesezodiac"],
    id: "snakechinesezodiac",
    munzee_id: 1278,
    state: TypeState.Physical,
    zodiac: "chinese",
  },
  {
    name: "Horse Chinese Zodiac",
    icons: ["horsechinesezodiac"],
    id: "horsechinesezodiac",
    munzee_id: 1279,
    state: TypeState.Physical,
    zodiac: "chinese",
  },
  {
    name: "Goat Chinese Zodiac",
    icons: ["goatchinesezodiac"],
    id: "goatchinesezodiac",
    munzee_id: 1280,
    state: TypeState.Physical,
    zodiac: "chinese",
  },
  {
    name: "Monkey Chinese Zodiac",
    icons: ["monkeychinesezodiac"],
    id: "monkeychinesezodiac",
    munzee_id: 1281,
    state: TypeState.Physical,
    zodiac: "chinese",
  },
  {
    name: "Rooster Chinese Zodiac",
    icons: ["roosterchinesezodiac"],
    id: "roosterchinesezodiac",
    munzee_id: 1282,
    state: TypeState.Physical,
    zodiac: "chinese",
  },
  {
    name: "The Nile",
    icons: ["nile"],
    id: "nile",
    munzee_id: 2751,
    state: TypeState.Virtual,
    zodiac: "egyptian",
  },
  {
    name: "Amon-Ra",
    icons: ["amon-ra"],
    id: "amon-ra",
    munzee_id: 2752,
    state: TypeState.Virtual,
    zodiac: "egyptian",
  },
  {
    name: "Osiris",
    icons: ["osiris"],
    id: "osiris",
    munzee_id: 2753,
    state: TypeState.Virtual,
    zodiac: "egyptian",
  },
  {
    name: "Thoth",
    icons: ["thoth"],
    id: "thoth",
    munzee_id: 2754,
    state: TypeState.Virtual,
    zodiac: "egyptian",
  },
  {
    name: "Horus",
    icons: ["horus"],
    id: "horus",
    munzee_id: 2755,
    state: TypeState.Virtual,
    zodiac: "egyptian",
  },
  {
    name: "Seth",
    icons: ["seth"],
    id: "seth",
    munzee_id: 2756,
    state: TypeState.Virtual,
    zodiac: "egyptian",
  },
  {
    name: "Anubis",
    icons: ["anubis"],
    id: "anubis",
    munzee_id: 2757,
    state: TypeState.Virtual,
    zodiac: "egyptian",
  },
];

export default zodiacs;