import { TypeHidden, TypeQuery, TypeState, TypeTags } from "@cuppazee/db/lib";

const nomads: {
  name: string;
  icons: string[];
  id: string;
  munzee_id?: number;
  state: "bouncer";
  lands_on: TypeQuery[];
  hidden?: TypeHidden[];
}[] = [
  {
    name: "Nomad",
    icons: ["nomad"],
    id: "nomad",
    munzee_id: 296,
    state: "bouncer",
    lands_on: ["munzee"],
  },
  {
    name: "Nomad Virtual",
    icons: ["nomadvirtual"],
    id: "nomadvirtual",
    munzee_id: 297,
    state: "bouncer",
    lands_on: [":virtual"],
  },
  {
    name: "Nomad Mystery",
    icons: ["nomadmystery"],
    id: "nomadmystery",
    munzee_id: 521,
    state: "bouncer",
    lands_on: ["mystery"],
  },
  {
    name: "Jewel Thief Nomad",
    icons: ["jewelthiefnomad"],
    id: "jewelthiefnomad",
    munzee_id: 822,
    state: "bouncer",
    lands_on: [type => type.has_tag(TypeTags.TypeJewel) && type.state === TypeState.Physical],
  },
  {
    name: "Bellhop Nomad",
    icons: ["bellhopnomad"],
    id: "bellhopnomad",
    munzee_id: 823,
    state: "bouncer",
    lands_on: [
      type =>
        type.has_tags(TypeTags.TypeDestination) &&
        type.has_tags(TypeTags.DestinationRooms) &&
        type.state === TypeState.Physical,
    ],
  },
  {
    name: "Pirate Nomad",
    icons: ["piratenomad"],
    id: "piratenomad",
    munzee_id: 824,
    state: "bouncer",
    lands_on: [":reseller"],
  },
  {
    name: "Warrior Nomad",
    icons: ["warriornomad"],
    id: "warriornomad",
    munzee_id: 999,
    state: "bouncer",
    lands_on: [type => type.has_tag(TypeTags.TypeWeaponClan) && type.state === TypeState.Physical],
  },
  {
    name: "Traveler Nomad",
    icons: ["travelernomad"],
    id: "travelernomad",
    munzee_id: 1580,
    state: "bouncer",
    lands_on: [":poi"],
  },
  {
    name: "Seasonal Nomad",
    icons: ["seasonalnomad"],
    id: "seasonalnomad",
    munzee_id: 1637,
    state: "bouncer",
    lands_on: [type => type.has_tag(TypeTags.TypeSeasonal) && type.state === TypeState.Physical],
  },
  {
    name: "Virtual Flat Nomad",
    icons: ["virtualflatnomad"],
    id: "virtualflatnomad",
    munzee_id: 1691,
    state: "bouncer",
    lands_on: [type => type.has_tag(TypeTags.TypeFlat) && type.state === TypeState.Virtual],
  },
  {
    name: "Coupe Champion Nomad",
    icons: ["coupechampionnomad"],
    id: "coupechampionnomad",
    munzee_id: 2074,
    state: "bouncer",
    lands_on: ["munzee"],
  },
  {
    name: "Coupe Champions #1",
    icons: ["coupechampions#1"],
    id: "coupechampions#1",
    munzee_id: 2075,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #2",
    icons: ["coupechampions#2"],
    id: "coupechampions#2",
    munzee_id: 2076,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #3",
    icons: ["coupechampions#3"],
    id: "coupechampions#3",
    munzee_id: 2077,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #4",
    icons: ["coupechampions#4"],
    id: "coupechampions#4",
    munzee_id: 2078,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #5",
    icons: ["coupechampions#5"],
    id: "coupechampions#5",
    munzee_id: 2079,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #6",
    icons: ["coupechampions#6"],
    id: "coupechampions#6",
    munzee_id: 2080,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #7",
    icons: ["coupechampions#7"],
    id: "coupechampions#7",
    munzee_id: 2081,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #8",
    icons: ["coupechampions#8"],
    id: "coupechampions#8",
    munzee_id: 2082,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #9",
    icons: ["coupechampions#9"],
    id: "coupechampions#9",
    munzee_id: 2083,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #10",
    icons: ["coupechampions#10"],
    id: "coupechampions#10",
    munzee_id: 2084,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #11",
    icons: ["coupechampions#11"],
    id: "coupechampions#11",
    munzee_id: 2085,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #12",
    icons: ["coupechampions#12"],
    id: "coupechampions#12",
    munzee_id: 2086,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #13",
    icons: ["coupechampions#13"],
    id: "coupechampions#13",
    munzee_id: 2087,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #14",
    icons: ["coupechampions#14"],
    id: "coupechampions#14",
    munzee_id: 2088,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #15",
    icons: ["coupechampions#15"],
    id: "coupechampions#15",
    munzee_id: 2089,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #16",
    icons: ["coupechampions#16"],
    id: "coupechampions#16",
    munzee_id: 2090,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #17",
    icons: ["coupechampions#17"],
    id: "coupechampions#17",
    munzee_id: 2091,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #18",
    icons: ["coupechampions#18"],
    id: "coupechampions#18",
    munzee_id: 2092,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #19",
    icons: ["coupechampions#19"],
    id: "coupechampions#19",
    munzee_id: 2093,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #20",
    icons: ["coupechampions#20"],
    id: "coupechampions#20",
    munzee_id: 2094,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #21",
    icons: ["coupechampions#21"],
    id: "coupechampions#21",
    munzee_id: 2095,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #22",
    icons: ["coupechampions#22"],
    id: "coupechampions#22",
    munzee_id: 2096,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Coupe Champions #23",
    icons: ["coupechampions#23"],
    id: "coupechampions#23",
    munzee_id: 2097,
    state: "bouncer",
    lands_on: ["munzee"],
    hidden: [TypeHidden.Bouncers],
  },
  {
    name: "Virtual ZeeCret Agent Nomad",
    icons: ["virtualzeecretagentnomad"],
    id: "virtualzeecretagentnomad",
    munzee_id: 2641,
    state: "bouncer",
    lands_on: ["nightvisiongoggles"],
  },
  {
    name: "ZeeCret Agent Nomad",
    icons: ["zeecretagentnomad"],
    id: "zeecretagentnomad",
    munzee_id: 2640,
    state: "bouncer",
    lands_on: ["briefcase"],
  },
  {
    name: "Virtual Gaming Nomad",
    icons: ["virtualgamingnomad"],
    id: "virtualgamingnomad",
    munzee_id: 2658,
    state: "bouncer",
    lands_on: [
      type =>
        type.has_tag(TypeTags.TypeGaming) &&
        !type.has_tag(TypeTags.Scatter) &&
        type.state === TypeState.Virtual,
    ],
  },
  {
    name: "Gaming Nomad",
    icons: ["gamingnomad"],
    id: "gamingnomad",
    munzee_id: 2657,
    state: "bouncer",
    lands_on: [
      type =>
        type.has_tag(TypeTags.TypeGaming) &&
        !type.has_tag(TypeTags.Scatter) &&
        type.state === TypeState.Physical,
    ],
  },
  {
    name: "Virtual Jewel Thief Nomad",
    icons: ["virtualjewelthiefnomad"],
    id: "virtualjewelthiefnomad",
    munzee_id: 2654,
    state: "bouncer",
    lands_on: [type => type.has_tag(TypeTags.TypeJewel) && type.state === TypeState.Virtual],
  },
  {
    name: "Virtual Warrior Nomad",
    icons: ["virtualwarriornomad"],
    id: "virtualwarriornomad",
    munzee_id: 2656,
    state: "bouncer",
    lands_on: [type => type.has_tag(TypeTags.TypeWeaponClan) && type.state === TypeState.Virtual],
  },
  {
    name: "Virtual Bellhop Nomad",
    icons: ["virtualbellhopnomad"],
    id: "virtualbellhopnomad",
    state: "bouncer",
    lands_on: [type => type.has_tag(TypeTags.TypeDestination) && type.state === TypeState.Virtual],
  },
];

export default nomads;