import { TypeHidden, TypeMeta, TypePoints, TypeQuery, TypeTags } from "@cuppazee/db";


const points: {
  [key: string]: TypePoints;
} = {
  bouncer_pc_1: {
    capture: 200,
    deploy: 250,
    capon: 100,
  },
  bouncer_pc_2: {
    capture: 300,
    capon: 200,
  },
  bouncer_pc_3: {
    capture: 500,
    capon: 300,
  },
  bouncer_gpc_1: {
    capture: 400,
    deploy: 500,
    capon: 200,
  },
  bouncer_gpc_2: {
    capture: 600,
    capon: 400,
  },
  bouncer_gpc_3: {
    capture: 1000,
    capon: 600,
  },
  gen_megu: {
    capture: 400,
    capon: 100,
  },
  funfinity: {
    deploy: 250,
    capture: 200,
    capon: 250,
  },
};

const pouch: {
  name: string;
  icons: string[];
  id: string;
  munzee_id?: number;
  stage?: number;
  set: "season_1" | "season_2" | "funfinity";
  points?: TypePoints;
  tags?: TypeTags[];
  lands_on: TypeQuery[];
  hidden?: TypeHidden[];
  meta?: TypeMeta;
  base?: string;
}[] = [
  {
    name: "Tuli",
    icons: ["tuli"],
    id: "tuli",
    munzee_id: 1240,
    base: "tuli",
    stage: 1,
    lands_on: ["treehouse", "munzee", "firemystery"],
    set: "season_1",
    points: points.bouncer_pc_1,
  },
  {
    name: "Tulimber",
    icons: ["tulimber"],
    id: "tulimber",
    munzee_id: 1241,
    base: "tuli",
    stage: 2,
    lands_on: ["munzee", "firemystery"],
    set: "season_1",
    points: points.bouncer_pc_2,
  },
  {
    name: "Tuliferno",
    icons: ["tuliferno"],
    id: "tuliferno",
    munzee_id: 1242,
    base: "tuli",
    stage: 3,
    lands_on: ["munzee", "firemystery"],
    set: "season_1",
    points: points.bouncer_pc_3,
  },
  {
    name: "Vesi",
    icons: ["vesi"],
    id: "vesi",
    munzee_id: 1370,
    base: "vesi",
    stage: 1,
    lands_on: ["treehouse", "munzee", "watermystery"],
    set: "season_1",
    points: points.bouncer_pc_1,
  },
  {
    name: "Vesial",
    icons: ["vesial"],
    id: "vesial",
    munzee_id: 1371,
    base: "vesi",
    stage: 2,
    lands_on: ["munzee", "watermystery"],
    set: "season_1",
    points: points.bouncer_pc_2,
  },
  {
    name: "Vesisaur",
    icons: ["vesisaur"],
    id: "vesisaur",
    munzee_id: 1372,
    base: "vesi",
    stage: 3,
    lands_on: ["munzee", "watermystery"],
    set: "season_1",
    points: points.bouncer_pc_3,
  },
  {
    name: "Muru",
    icons: ["muru"],
    id: "muru",
    munzee_id: 1638,
    base: "muru",
    stage: 1,
    lands_on: ["treehouse", "munzee", "earthmystery"],
    set: "season_1",
    points: points.bouncer_pc_1,
  },
  {
    name: "Muruchi",
    icons: ["muruchi"],
    id: "muruchi",
    munzee_id: 1639,
    base: "muru",
    stage: 2,
    lands_on: ["munzee", "earthmystery"],
    set: "season_1",
    points: points.bouncer_pc_2,
  },
  {
    name: "Murutain",
    icons: ["murutain"],
    id: "murutain",
    munzee_id: 1640,
    base: "muru",
    stage: 3,
    lands_on: ["munzee", "earthmystery"],
    set: "season_1",
    points: points.bouncer_pc_3,
  },
  {
    name: "Mitmegu",
    icons: ["mitmegu"],
    id: "mitmegu",
    munzee_id: 1752,
    base: "mitmegu",
    lands_on: [
      "treehouse",
      "munzee",
      "shamrock",
      "scatter",
      "premium",
      "rockpaperscissors",
      "watermystery",
      "earthmystery",
      "firemystery",
    ],
    set: "season_1",
    points: {
      capture: 200,
      deploy: 250,
      capon: 100,
    },
  },
  {
    name: "Jootmegu",
    icons: ["jootmegu"],
    id: "jootmegu",
    munzee_id: 1753,
    base: "mitmegu",
    lands_on: ["watermystery"],
    set: "season_1",
    points: points.gen_megu,
  },
  {
    name: "Rohimegu",
    icons: ["rohimegu"],
    id: "rohimegu",
    munzee_id: 1754,
    base: "mitmegu",
    lands_on: ["earthmystery"],
    set: "season_1",
    points: points.gen_megu,
  },
  {
    name: "Lokemegu",
    icons: ["lokemegu"],
    id: "lokemegu",
    munzee_id: 1755,
    base: "mitmegu",
    lands_on: ["firemystery"],
    set: "season_1",
    points: points.gen_megu,
  },
  {
    name: "Gleaming Muru",
    icons: ["gleamingmuru"],
    id: "gleamingmuru",
    munzee_id: 1850,
    base: "muru",
    tags: [TypeTags.BouncerPCGleaming],
    hidden: [TypeHidden.Bouncers, TypeHidden.Deploy],
    stage: 1,
    lands_on: ["treehouse", "munzee", "earthmystery"],
    set: "season_1",
    points: points.bouncer_gpc_1,
  },
  {
    name: "Gleaming Muruchi",
    icons: ["gleamingmuruchi"],
    id: "gleamingmuruchi",
    munzee_id: 1851,
    base: "muru",
    tags: [TypeTags.BouncerPCGleaming],
    hidden: [TypeHidden.Bouncers, TypeHidden.Deploy],
    stage: 2,
    lands_on: ["munzee", "earthmystery"],
    set: "season_1",
    points: points.bouncer_gpc_2,
  },
  {
    name: "Gleaming Murutain",
    icons: ["gleamingmurutain"],
    id: "gleamingmurutain",
    munzee_id: 1852,
    base: "muru",
    tags: [TypeTags.BouncerPCGleaming],
    hidden: [TypeHidden.Bouncers, TypeHidden.Deploy],
    stage: 3,
    lands_on: ["munzee", "earthmystery"],
    set: "season_1",
    points: points.bouncer_gpc_3,
  },
  {
    name: "Gleaming Tuli",
    icons: ["gleamingtuli"],
    id: "gleamingtuli",
    munzee_id: 1853,
    base: "tuli",
    tags: [TypeTags.BouncerPCGleaming],
    hidden: [TypeHidden.Bouncers, TypeHidden.Deploy],
    stage: 1,
    lands_on: ["treehouse", "munzee", "firemystery"],
    set: "season_1",
    points: points.bouncer_gpc_1,
  },
  {
    name: "Gleaming Tulimber",
    icons: ["gleamingtulimber"],
    id: "gleamingtulimber",
    munzee_id: 1854,
    base: "tuli",
    tags: [TypeTags.BouncerPCGleaming],
    hidden: [TypeHidden.Bouncers, TypeHidden.Deploy],
    stage: 2,
    lands_on: ["munzee", "firemystery"],
    set: "season_1",
    points: points.bouncer_gpc_2,
  },
  {
    name: "Gleaming Tuliferno",
    icons: ["gleamingtuliferno"],
    id: "gleamingtuliferno",
    munzee_id: 1855,
    base: "tuli",
    tags: [TypeTags.BouncerPCGleaming],
    hidden: [TypeHidden.Bouncers, TypeHidden.Deploy],
    stage: 3,
    lands_on: ["munzee", "firemystery"],
    set: "season_1",
    points: points.bouncer_gpc_3,
  },
  {
    name: "Gleaming Vesi",
    icons: ["gleamingvesi"],
    id: "gleamingvesi",
    munzee_id: 1856,
    base: "vesi",
    tags: [TypeTags.BouncerPCGleaming],
    hidden: [TypeHidden.Bouncers, TypeHidden.Deploy],
    stage: 1,
    lands_on: ["treehouse", "munzee", "watermystery"],
    set: "season_1",
    points: points.bouncer_gpc_1,
  },
  {
    name: "Gleaming Vesial",
    icons: ["gleamingvesial"],
    id: "gleamingvesial",
    munzee_id: 1857,
    base: "vesi",
    tags: [TypeTags.BouncerPCGleaming],
    hidden: [TypeHidden.Bouncers, TypeHidden.Deploy],
    stage: 2,
    lands_on: ["munzee", "watermystery"],
    set: "season_1",
    points: points.bouncer_gpc_2,
  },
  {
    name: "Gleaming Vesisaur",
    icons: ["gleamingvesisaur"],
    id: "gleamingvesisaur",
    munzee_id: 1858,
    base: "vesi",
    tags: [TypeTags.BouncerPCGleaming],
    hidden: [TypeHidden.Bouncers, TypeHidden.Deploy],
    stage: 3,
    lands_on: ["munzee", "watermystery"],
    set: "season_1",
    points: points.bouncer_gpc_3,
  },
  {
    name: "Pimedus",
    icons: ["pimedus"],
    id: "pimedus",
    munzee_id: 1919,
    lands_on: [
      "skyland",
      "treehouse",
      "munzee",
      ":reseller",
      type => type.has_tag(TypeTags.TypeZodiacChinese),
      "virtual_sapphire",
      "briefcase",
      "thehammer",
      "crossbow",
      "catapult",
    ],
    set: "season_1",
  },
  {
    name: "Puffle",
    icons: ["puffle"],
    id: "puffle",
    munzee_id: 2240,
    base: "puffle",
    stage: 1,
    lands_on: ["skyland", type => type.has_tag(TypeTags.TypeVirtual), "airmystery"],
    set: "season_2",
    points: points.bouncer_pc_1,
  },
  {
    name: "Pufrain",
    icons: ["pufrain"],
    id: "pufrain",
    munzee_id: 2241,
    base: "puffle",
    stage: 2,
    lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "airmystery"],
    set: "season_2",
    points: points.bouncer_pc_2,
  },
  {
    name: "Puflawn",
    icons: ["puflawn"],
    id: "puflawn",
    munzee_id: 2242,
    base: "puffle",
    stage: 3,
    lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "airmystery"],
    set: "season_2",
    points: points.bouncer_pc_3,
  },
  {
    name: "Magnetus",
    icons: ["magnetus"],
    id: "magnetus",
    munzee_id: 2306,
    lands_on: [
      "skyland",
      "treehouse",
      "munzee",
      "airmystery",
      type => type.has_tag(TypeTags.VirtualColourBlue),
      type => type.has_tag(TypeTags.VirtualColourRed),
      "watermystery",
      "joystickvirtual",
      "joystick",
      "virtual_yellow",
      "virtual_goldenrod",
      "virtual_dandelion",
    ],
    set: "season_2",
  },
  {
    name: "Topaas",
    icons: ["topaas"],
    id: "topaas",
    munzee_id: 2366,
    lands_on: ["treehouse", "munzee", "earthmystery", "topaz", "treehouse"],
    set: "funfinity",
    points: points.funfinity,
  },
  {
    name: "Ametust",
    icons: ["ametust"],
    id: "ametust",
    munzee_id: 2367,
    lands_on: [
      "skyland",
      type => type.has_tag(TypeTags.TypeVirtual),
      "earthmystery",
      "virtual_amethyst",
      "treehouse",
    ],
    set: "funfinity",
    points: points.funfinity,
  },
  {
    name: "Oniks",
    icons: ["oniks"],
    id: "oniks",
    munzee_id: 2368,
    lands_on: [
      "skyland",
      type => type.has_tag(TypeTags.TypeVirtual),
      "earthmystery",
      "virtual_onyx",
      "treehouse",
    ],
    set: "funfinity",
    points: points.funfinity,
  },
  {
    name: "Elekter",
    icons: ["elekter"],
    id: "elekter",
    munzee_id: 2407,
    base: "elekter",
    stage: 1,
    lands_on: ["skyland", type => type.has_tag(TypeTags.TypeVirtual), "electricmystery"],
    set: "season_2",
    points: points.ouncer_pc_1,
  },
  {
    name: "Elekjoud",
    icons: ["elekjoud"],
    id: "elekjoud",
    munzee_id: 2408,
    base: "elekter",
    stage: 2,
    lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "electricmystery"],
    set: "season_2",
    points: points.ouncer_pc_2,
  },
  {
    name: "Elektrivool",
    icons: ["elektrivool"],
    id: "elektrivool",
    munzee_id: 2409,
    base: "elekter",
    stage: 3,
    lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "electricmystery"],
    set: "season_2",
    points: points.ouncer_pc_3,
  },
  {
    name: "Teemant",
    icons: ["teemant"],
    id: "teemant",
    munzee_id: 2369,
    lands_on: ["treehouse", "munzee", "earthmystery", "diamond"],
    set: "funfinity",
    points: points.funfinity,
  },
  {
    name: "Smaragd",
    icons: ["smaragd"],
    id: "smaragd",
    munzee_id: 2370,
    lands_on: [
      "skyland",
      type => type.has_tag(TypeTags.VirtualColourGreen),
      "airmystery",
      "virtual_emerald",
    ],
    set: "funfinity",
    points: points.funfinity,
  },
  {
    name: "Akvamariin",
    icons: ["akvamariin"],
    id: "akvamariin",
    munzee_id: 2374,
    lands_on: ["treehouse", "munzee", "earthmystery", "aquamarine"],
    set: "funfinity",
    points: points.funfinity,
  },
  {
    name: "Rubiin",
    icons: ["rubiin"],
    id: "rubiin",
    munzee_id: 2371,
    lands_on: ["treehouse", "munzee", "firemystery", "ruby"],
    set: "funfinity",
    points: points.funfinity,
  },
  {
    name: "Safiir",
    icons: ["safiir"],
    id: "safiir",
    munzee_id: 2372,
    lands_on: [
      "skyland",
      type => type.has_tag(TypeTags.TypeVirtual),
      "airmystery",
      "virtual_sapphire",
    ],
    set: "funfinity",
    points: points.funfinity,
  },
  {
    name: "Roosa",
    icons: ["roosa"],
    id: "roosa",
    munzee_id: 2375,
    lands_on: ["treehouse", "munzee", "firemystery", "pinkdiamond"],
    set: "funfinity",
    points: points.funfinity,
  },
  {
    name: "Tsitriin",
    icons: ["tsitriin"],
    id: "tsitriin",
    munzee_id: 2373,
    lands_on: [
      type => type.has_tag(TypeTags.TypeVirtual),
      "airmystery",
      "virtual_citrine",
      "skyland",
    ],
    set: "funfinity",
    points: points.funfinity,
  },
];

export default pouch;