import { TypeQuery, TypeMeta, TypeState, TypeTags } from "@cuppazee/db";

const retired: {
  name: string;
  icons: string[];
  id: string;
  munzee_id?: number;
  tags?: TypeTags[];
  lands_on: TypeQuery[];
  meta?: TypeMeta;
  duration?: number;
}[] = [
  {
    name: "Retired Unicorn",
    icons: ["retiredunicorn"],
    id: "retiredunicorn",
    munzee_id: 1535,
    lands_on: ["munzee", "shamrock"],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Leprechaun",
    icons: ["retiredleprechaun"],
    id: "retiredleprechaun",
    munzee_id: 1536,
    lands_on: ["munzee", "shamrock"],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Dragon",
    icons: ["retireddragon"],
    id: "retireddragon",
    munzee_id: 1537,
    lands_on: ["munzee", "firemystery"],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Yeti",
    icons: ["retiredyeti"],
    id: "retiredyeti",
    munzee_id: 1538,
    lands_on: ["munzee", "icemystery"],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Faun",
    icons: ["retiredfaun"],
    id: "retiredfaun",
    munzee_id: 1539,
    lands_on: ["munzee", "earthmystery"],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Hydra",
    icons: ["retiredhydra"],
    id: "retiredhydra",
    munzee_id: 1540,
    lands_on: ["munzee", "watermystery"],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Mermaid",
    icons: ["retiredmermaid"],
    id: "retiredmermaid",
    munzee_id: 1541,
    lands_on: [
      "munzee",
      "watermystery",
      type => type.has_tag(TypeTags.TypeJewel) && type.state === TypeState.Physical,
    ],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Pegasus",
    icons: ["retiredpegasus"],
    id: "retiredpegasus",
    munzee_id: 1542,
    lands_on: [type => type.has_tag(TypeTags.TypeVirtual), "airmystery", "electricmystery"],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Cyclops",
    icons: ["retiredcyclops"],
    id: "retiredcyclops",
    munzee_id: 1543,
    lands_on: [type => type.has_tag(TypeTags.TypeJewel) && type.munzee_id !== 148],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Fairy",
    icons: ["retiredfairy"],
    id: "retiredfairy",
    munzee_id: 2051,
    lands_on: ["munzee", "airmystery", "mystery"],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Banshee",
    icons: ["retiredbanshee"],
    id: "retiredbanshee",
    munzee_id: 2052,
    lands_on: [
      "munzee",
      "shamrock",
      "airmystery",
      type => type.has_tag(TypeTags.VirtualColourBlack),
      type => type.has_tag(TypeTags.VirtualColourGreen),
    ],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Zombie Tuli",
    icons: ["zombietuli"],
    id: "zombietuli",
    munzee_id: 2053,
    lands_on: ["munzee", "firemystery"],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerPCZombie, TypeTags.BouncerRetired],
  },
  {
    name: "Zombie Vesi",
    icons: ["zombievesi"],
    id: "zombievesi",
    munzee_id: 2054,
    lands_on: ["munzee", "watermystery"],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerPCZombie, TypeTags.BouncerRetired],
  },
  {
    name: "Zombie Muru",
    icons: ["zombiemuru"],
    id: "zombiemuru",
    munzee_id: 2055,
    lands_on: ["munzee", "earthmystery"],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerPCZombie, TypeTags.BouncerRetired],
  },
  {
    name: "Zombie Elekter",
    icons: ["zombieelekter"],
    id: "zombieelekter",
    lands_on: ["skyland", type => type.has_tag(TypeTags.TypeVirtual), "electricmystery"],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerPCZombie, TypeTags.BouncerRetired],
  },
  {
    name: "Zombie Puffle",
    icons: ["zombiepuffle"],
    id: "zombiepuffle",
    munzee_id: 2822,
    lands_on: ["skyland", type => type.has_tag(TypeTags.TypeVirtual), "airmystery"],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerPCZombie, TypeTags.BouncerRetired],
  },
  {
    name: "Zombie Magnetus",
    icons: ["zombiemagnetus"],
    id: "zombiemagnetus",
    lands_on: [
      "skyland",
      "treehouse",
      "munzee",
      "airmystery",
      type => type.has_tag(TypeTags.VirtualColourBlue),
      type => type.has_tag(TypeTags.VirtualColourRed),
      "watermystery",
      "joystickvirtual",
      "joystick",
      "virtual_yellow",
      "virtual_goldenrod",
      "virtual_dandelion",
    ],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerPCZombie, TypeTags.BouncerRetired],
  },
  {
    name: "Zombie Pimedus",
    icons: ["zombiepimedus"],
    id: "zombiepimedus",
    lands_on: [
      "skyland",
      "treehouse",
      "munzee",
      ":reseller",
      type => type.has_tag(TypeTags.TypeZodiacChinese),
      "virtual_sapphire",
      "briefcase",
      "thehammer",
      "crossbow",
      "catapult",
    ],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerPCZombie, TypeTags.BouncerRetired],
  },
  {
    name: "Retired Nymph",
    icons: ["retirednymph"],
    id: "retirednymph",
    lands_on: [
      "skyland",
      "treehouse",
      "munzee",
      "earthmystery",
      type => type.has_tag(TypeTags.VirtualColourBrown),
      type => type.has_tag(TypeTags.VirtualColourBlack),
      type => type.has_tag(TypeTags.VirtualColourGreen),
    ],
    tags: [TypeTags.BouncerMyth, TypeTags.BouncerRetired],
  },
  {
    name: "Phantom Flat Rob",
    icons: ["phantomflatrob"],
    id: "phantomflatrob",
    munzee_id: 2817,
    lands_on: [],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerFlatPhantom, TypeTags.BouncerRetired],
  },
  {
    name: "Phantom Flat Matt",
    icons: ["phantomflatmatt"],
    id: "phantomflatmatt",
    lands_on: [],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerFlatPhantom, TypeTags.BouncerRetired],
  },
  {
    name: "Phantom Flat Lou",
    icons: ["phantomflatlou"],
    id: "phantomflatlou",
    lands_on: [],
    duration: 6,
    tags: [TypeTags.BouncerPC, TypeTags.BouncerFlatPhantom, TypeTags.BouncerRetired],
  },
];

export default retired;
