import { TypeQuery, TypeState, TypeTags } from "@cuppazee/db";

const mythhosts: {
  name: string;
  icons: string[];
  id: string;
  munzee_id?: number;
  state: TypeState;
  hosts: TypeQuery[];
  tags?: TypeTags[];
}[] = [
  {
    name: "Unicorn Host",
    icons: ["unicornhost"],
    id: "unicornhost",
    munzee_id: 506,
    state: TypeState.Physical,
    hosts: [505],
    tags: [TypeTags.BouncerHostMythOriginal],
  },
  {
    name: "Leprechaun Host",
    icons: ["leprechaunhost"],
    id: "leprechaunhost",
    munzee_id: 509,
    state: TypeState.Physical,
    hosts: [508, 1646, 1647],
    tags: [TypeTags.BouncerHostMythOriginal],
  },
  {
    name: "Dragon Host",
    icons: ["dragonhost"],
    id: "dragonhost",
    munzee_id: 574,
    state: TypeState.Physical,
    hosts: [573, 1874, 1875],
    tags: [TypeTags.BouncerHostMythOriginal],
  },
  {
    name: "Yeti Host",
    icons: ["yetihost"],
    id: "yetihost",
    munzee_id: 726,
    state: TypeState.Physical,
    hosts: [725],
    tags: [TypeTags.BouncerHostMythOriginal],
  },
  {
    name: "Faun Host",
    icons: ["faunhost"],
    id: "faunhost",
    munzee_id: 854,
    state: TypeState.Physical,
    hosts: [853.1997, 1998],
    tags: [TypeTags.BouncerHostMythClassical],
  },
  {
    name: "Hydra Host",
    icons: ["hydrahost"],
    id: "hydrahost",
    munzee_id: 954,
    state: TypeState.Physical,
    hosts: [953, 2252, 2253],
    tags: [TypeTags.BouncerHostMythClassical],
  },
  {
    name: "Pegasus Host",
    icons: ["pegasushost"],
    id: "pegasushost",
    munzee_id: 1101,
    state: TypeState.Virtual,
    hosts: [1100, 1995, 1996],
    tags: [TypeTags.BouncerHostMythClassical],
  },
  {
    name: "Cyclops Host",
    icons: ["cyclopshost"],
    id: "cyclopshost",
    munzee_id: 1169,
    state: TypeState.Physical,
    hosts: [1168],
    tags: [TypeTags.BouncerHostMythClassical],
  },
  {
    name: "Cyclops Virtual Host",
    icons: ["cyclops_virtual_host"],
    id: "cyclops_virtual_host",
    munzee_id: 1170,
    state: TypeState.Virtual,
    hosts: [1168],
    tags: [TypeTags.BouncerHostMythClassical],
  },
  {
    name: "Mermaid Host",
    icons: ["mermaidhost"],
    id: "mermaidhost",
    munzee_id: 1379,
    state: TypeState.Physical,
    hosts: [1378, 1648, 1649],
    tags: [TypeTags.BouncerHostMythMirror],
  },
  {
    name: "Fairy Host",
    icons: ["fairyhost"],
    id: "fairyhost",
    munzee_id: 1545,
    state: TypeState.Physical,
    hosts: [1544],
    tags: [TypeTags.BouncerHostMythMirror],
  },
  {
    name: "Fairy Virtual Host",
    icons: ["fairy_virtual_host"],
    id: "fairy_virtual_host",
    munzee_id: 1546,
    state: TypeState.Virtual,
    hosts: [1544],
    tags: [TypeTags.BouncerHostMythMirror],
  },
  {
    name: "Mermaid Virtual Host",
    icons: ["mermaid_virtual_host"],
    id: "mermaid_virtual_host",
    munzee_id: 1650,
    state: TypeState.Virtual,
    hosts: [1649],
    tags: [TypeTags.BouncerHostMythMirror],
  },
  {
    name: "Leprechaun Virtual Host",
    icons: ["leprechaun_virtual_host"],
    id: "leprechaun_virtual_host",
    munzee_id: 1651,
    state: TypeState.Virtual,
    hosts: [1646, 1647],
    tags: [TypeTags.BouncerHostMythOriginal],
  },
  {
    name: "Banshee Host",
    icons: ["bansheehost"],
    id: "bansheehost",
    munzee_id: 1828,
    state: TypeState.Physical,
    hosts: [1827, 2254, 2255],
    tags: [TypeTags.BouncerHostMythMirror],
  },
  {
    name: "Banshee Virtual Host",
    icons: ["banshee_virtual_host"],
    id: "banshee_virtual_host",
    munzee_id: 1829,
    state: TypeState.Virtual,
    hosts: [1827, 2254, 2255],
    tags: [TypeTags.BouncerHostMythMirror],
  },
  {
    name: "Dragon Virtual Host",
    icons: ["dragon_virtual_host"],
    id: "dragon_virtual_host",
    munzee_id: 1878,
    state: TypeState.Virtual,
    hosts: [1874, 1875],
    tags: [TypeTags.BouncerHostMythOriginal],
  },
  {
    name: "Pegasus Physical Host",
    icons: ["pegasusphysicalhost"],
    id: "pegasusphysicalhost",
    munzee_id: 1999,
    state: TypeState.Physical,
    hosts: [1995, 1996],
    tags: [TypeTags.BouncerHostMythClassical],
  },
  {
    name: "Faun Virtual Host",
    icons: ["faunvirtualhost"],
    id: "faunvirtualhost",
    munzee_id: 2000,
    state: TypeState.Virtual,
    hosts: [1997, 1998],
    tags: [TypeTags.BouncerHostMythClassical],
  },
  {
    name: "Nymph Host",
    icons: ["nymphhost"],
    id: "nymphhost",
    munzee_id: 2119,
    state: TypeState.Physical,
    hosts: [2118],
    tags: [TypeTags.BouncerHostMythMirror],
  },
  {
    name: "Nymph Virtual Host",
    icons: ["nymph_virtual_host"],
    id: "nymph_virtual_host",
    munzee_id: 2120,
    state: TypeState.Virtual,
    hosts: [2118],
    tags: [TypeTags.BouncerHostMythMirror],
  },
];

export default mythhosts;
